// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: block.proto
// Original file comments:
// block.proto
//
// A block bundles transactions together and chains them to the previous block.
// Miners verify incoming transactions and perform proof of work (finding a nonce
// such that the hash of the block header meets the difficulty target).
// The block contains everything needed to validate its contents and its
// position in the chain.
//
#ifndef GRPC_block_2eproto__INCLUDED
#define GRPC_block_2eproto__INCLUDED

#include "block.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace bitcoin {

}  // namespace bitcoin


#endif  // GRPC_block_2eproto__INCLUDED
