// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: block.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_block_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_block_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "transaction.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_block_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_block_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_block_2eproto;
namespace bitcoin {
class Block;
struct BlockDefaultTypeInternal;
extern BlockDefaultTypeInternal _Block_default_instance_;
}  // namespace bitcoin
PROTOBUF_NAMESPACE_OPEN
template<> ::bitcoin::Block* Arena::CreateMaybeMessage<::bitcoin::Block>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bitcoin {

// ===================================================================

class Block final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.Block) */ {
 public:
  inline Block() : Block(nullptr) {}
  ~Block() override;
  explicit PROTOBUF_CONSTEXPR Block(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Block(const Block& from);
  Block(Block&& from) noexcept
    : Block() {
    *this = ::std::move(from);
  }

  inline Block& operator=(const Block& from) {
    CopyFrom(from);
    return *this;
  }
  inline Block& operator=(Block&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Block& default_instance() {
    return *internal_default_instance();
  }
  static inline const Block* internal_default_instance() {
    return reinterpret_cast<const Block*>(
               &_Block_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Block& a, Block& b) {
    a.Swap(&b);
  }
  inline void Swap(Block* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Block* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Block* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Block>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Block& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Block& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Block* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.Block";
  }
  protected:
  explicit Block(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransactionIdsFieldNumber = 6,
    kTransactionsFieldNumber = 7,
    kPrevBlockHashFieldNumber = 1,
    kMerkleRootFieldNumber = 2,
    kTimestampFieldNumber = 3,
    kNonceFieldNumber = 5,
    kDifficultyTargetFieldNumber = 4,
  };
  // repeated bytes transaction_ids = 6;
  int transaction_ids_size() const;
  private:
  int _internal_transaction_ids_size() const;
  public:
  void clear_transaction_ids();
  const std::string& transaction_ids(int index) const;
  std::string* mutable_transaction_ids(int index);
  void set_transaction_ids(int index, const std::string& value);
  void set_transaction_ids(int index, std::string&& value);
  void set_transaction_ids(int index, const char* value);
  void set_transaction_ids(int index, const void* value, size_t size);
  std::string* add_transaction_ids();
  void add_transaction_ids(const std::string& value);
  void add_transaction_ids(std::string&& value);
  void add_transaction_ids(const char* value);
  void add_transaction_ids(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& transaction_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_transaction_ids();
  private:
  const std::string& _internal_transaction_ids(int index) const;
  std::string* _internal_add_transaction_ids();
  public:

  // repeated .bitcoin.Transaction transactions = 7;
  int transactions_size() const;
  private:
  int _internal_transactions_size() const;
  public:
  void clear_transactions();
  ::bitcoin::Transaction* mutable_transactions(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Transaction >*
      mutable_transactions();
  private:
  const ::bitcoin::Transaction& _internal_transactions(int index) const;
  ::bitcoin::Transaction* _internal_add_transactions();
  public:
  const ::bitcoin::Transaction& transactions(int index) const;
  ::bitcoin::Transaction* add_transactions();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Transaction >&
      transactions() const;

  // bytes prev_block_hash = 1;
  void clear_prev_block_hash();
  const std::string& prev_block_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prev_block_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prev_block_hash();
  PROTOBUF_NODISCARD std::string* release_prev_block_hash();
  void set_allocated_prev_block_hash(std::string* prev_block_hash);
  private:
  const std::string& _internal_prev_block_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prev_block_hash(const std::string& value);
  std::string* _internal_mutable_prev_block_hash();
  public:

  // bytes merkle_root = 2;
  void clear_merkle_root();
  const std::string& merkle_root() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_merkle_root(ArgT0&& arg0, ArgT... args);
  std::string* mutable_merkle_root();
  PROTOBUF_NODISCARD std::string* release_merkle_root();
  void set_allocated_merkle_root(std::string* merkle_root);
  private:
  const std::string& _internal_merkle_root() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_merkle_root(const std::string& value);
  std::string* _internal_mutable_merkle_root();
  public:

  // uint64 timestamp = 3;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // uint64 nonce = 5;
  void clear_nonce();
  uint64_t nonce() const;
  void set_nonce(uint64_t value);
  private:
  uint64_t _internal_nonce() const;
  void _internal_set_nonce(uint64_t value);
  public:

  // uint32 difficulty_target = 4;
  void clear_difficulty_target();
  uint32_t difficulty_target() const;
  void set_difficulty_target(uint32_t value);
  private:
  uint32_t _internal_difficulty_target() const;
  void _internal_set_difficulty_target(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:bitcoin.Block)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> transaction_ids_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Transaction > transactions_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prev_block_hash_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr merkle_root_;
  uint64_t timestamp_;
  uint64_t nonce_;
  uint32_t difficulty_target_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_block_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Block

// bytes prev_block_hash = 1;
inline void Block::clear_prev_block_hash() {
  prev_block_hash_.ClearToEmpty();
}
inline const std::string& Block::prev_block_hash() const {
  // @@protoc_insertion_point(field_get:bitcoin.Block.prev_block_hash)
  return _internal_prev_block_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Block::set_prev_block_hash(ArgT0&& arg0, ArgT... args) {
 
 prev_block_hash_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.Block.prev_block_hash)
}
inline std::string* Block::mutable_prev_block_hash() {
  std::string* _s = _internal_mutable_prev_block_hash();
  // @@protoc_insertion_point(field_mutable:bitcoin.Block.prev_block_hash)
  return _s;
}
inline const std::string& Block::_internal_prev_block_hash() const {
  return prev_block_hash_.Get();
}
inline void Block::_internal_set_prev_block_hash(const std::string& value) {
  
  prev_block_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* Block::_internal_mutable_prev_block_hash() {
  
  return prev_block_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* Block::release_prev_block_hash() {
  // @@protoc_insertion_point(field_release:bitcoin.Block.prev_block_hash)
  return prev_block_hash_.Release();
}
inline void Block::set_allocated_prev_block_hash(std::string* prev_block_hash) {
  if (prev_block_hash != nullptr) {
    
  } else {
    
  }
  prev_block_hash_.SetAllocated(prev_block_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (prev_block_hash_.IsDefault()) {
    prev_block_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.Block.prev_block_hash)
}

// bytes merkle_root = 2;
inline void Block::clear_merkle_root() {
  merkle_root_.ClearToEmpty();
}
inline const std::string& Block::merkle_root() const {
  // @@protoc_insertion_point(field_get:bitcoin.Block.merkle_root)
  return _internal_merkle_root();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Block::set_merkle_root(ArgT0&& arg0, ArgT... args) {
 
 merkle_root_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.Block.merkle_root)
}
inline std::string* Block::mutable_merkle_root() {
  std::string* _s = _internal_mutable_merkle_root();
  // @@protoc_insertion_point(field_mutable:bitcoin.Block.merkle_root)
  return _s;
}
inline const std::string& Block::_internal_merkle_root() const {
  return merkle_root_.Get();
}
inline void Block::_internal_set_merkle_root(const std::string& value) {
  
  merkle_root_.Set(value, GetArenaForAllocation());
}
inline std::string* Block::_internal_mutable_merkle_root() {
  
  return merkle_root_.Mutable(GetArenaForAllocation());
}
inline std::string* Block::release_merkle_root() {
  // @@protoc_insertion_point(field_release:bitcoin.Block.merkle_root)
  return merkle_root_.Release();
}
inline void Block::set_allocated_merkle_root(std::string* merkle_root) {
  if (merkle_root != nullptr) {
    
  } else {
    
  }
  merkle_root_.SetAllocated(merkle_root, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (merkle_root_.IsDefault()) {
    merkle_root_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.Block.merkle_root)
}

// uint64 timestamp = 3;
inline void Block::clear_timestamp() {
  timestamp_ = uint64_t{0u};
}
inline uint64_t Block::_internal_timestamp() const {
  return timestamp_;
}
inline uint64_t Block::timestamp() const {
  // @@protoc_insertion_point(field_get:bitcoin.Block.timestamp)
  return _internal_timestamp();
}
inline void Block::_internal_set_timestamp(uint64_t value) {
  
  timestamp_ = value;
}
inline void Block::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:bitcoin.Block.timestamp)
}

// uint32 difficulty_target = 4;
inline void Block::clear_difficulty_target() {
  difficulty_target_ = 0u;
}
inline uint32_t Block::_internal_difficulty_target() const {
  return difficulty_target_;
}
inline uint32_t Block::difficulty_target() const {
  // @@protoc_insertion_point(field_get:bitcoin.Block.difficulty_target)
  return _internal_difficulty_target();
}
inline void Block::_internal_set_difficulty_target(uint32_t value) {
  
  difficulty_target_ = value;
}
inline void Block::set_difficulty_target(uint32_t value) {
  _internal_set_difficulty_target(value);
  // @@protoc_insertion_point(field_set:bitcoin.Block.difficulty_target)
}

// uint64 nonce = 5;
inline void Block::clear_nonce() {
  nonce_ = uint64_t{0u};
}
inline uint64_t Block::_internal_nonce() const {
  return nonce_;
}
inline uint64_t Block::nonce() const {
  // @@protoc_insertion_point(field_get:bitcoin.Block.nonce)
  return _internal_nonce();
}
inline void Block::_internal_set_nonce(uint64_t value) {
  
  nonce_ = value;
}
inline void Block::set_nonce(uint64_t value) {
  _internal_set_nonce(value);
  // @@protoc_insertion_point(field_set:bitcoin.Block.nonce)
}

// repeated bytes transaction_ids = 6;
inline int Block::_internal_transaction_ids_size() const {
  return transaction_ids_.size();
}
inline int Block::transaction_ids_size() const {
  return _internal_transaction_ids_size();
}
inline void Block::clear_transaction_ids() {
  transaction_ids_.Clear();
}
inline std::string* Block::add_transaction_ids() {
  std::string* _s = _internal_add_transaction_ids();
  // @@protoc_insertion_point(field_add_mutable:bitcoin.Block.transaction_ids)
  return _s;
}
inline const std::string& Block::_internal_transaction_ids(int index) const {
  return transaction_ids_.Get(index);
}
inline const std::string& Block::transaction_ids(int index) const {
  // @@protoc_insertion_point(field_get:bitcoin.Block.transaction_ids)
  return _internal_transaction_ids(index);
}
inline std::string* Block::mutable_transaction_ids(int index) {
  // @@protoc_insertion_point(field_mutable:bitcoin.Block.transaction_ids)
  return transaction_ids_.Mutable(index);
}
inline void Block::set_transaction_ids(int index, const std::string& value) {
  transaction_ids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:bitcoin.Block.transaction_ids)
}
inline void Block::set_transaction_ids(int index, std::string&& value) {
  transaction_ids_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:bitcoin.Block.transaction_ids)
}
inline void Block::set_transaction_ids(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  transaction_ids_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:bitcoin.Block.transaction_ids)
}
inline void Block::set_transaction_ids(int index, const void* value, size_t size) {
  transaction_ids_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:bitcoin.Block.transaction_ids)
}
inline std::string* Block::_internal_add_transaction_ids() {
  return transaction_ids_.Add();
}
inline void Block::add_transaction_ids(const std::string& value) {
  transaction_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:bitcoin.Block.transaction_ids)
}
inline void Block::add_transaction_ids(std::string&& value) {
  transaction_ids_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:bitcoin.Block.transaction_ids)
}
inline void Block::add_transaction_ids(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  transaction_ids_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:bitcoin.Block.transaction_ids)
}
inline void Block::add_transaction_ids(const void* value, size_t size) {
  transaction_ids_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:bitcoin.Block.transaction_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Block::transaction_ids() const {
  // @@protoc_insertion_point(field_list:bitcoin.Block.transaction_ids)
  return transaction_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Block::mutable_transaction_ids() {
  // @@protoc_insertion_point(field_mutable_list:bitcoin.Block.transaction_ids)
  return &transaction_ids_;
}

// repeated .bitcoin.Transaction transactions = 7;
inline int Block::_internal_transactions_size() const {
  return transactions_.size();
}
inline int Block::transactions_size() const {
  return _internal_transactions_size();
}
inline ::bitcoin::Transaction* Block::mutable_transactions(int index) {
  // @@protoc_insertion_point(field_mutable:bitcoin.Block.transactions)
  return transactions_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Transaction >*
Block::mutable_transactions() {
  // @@protoc_insertion_point(field_mutable_list:bitcoin.Block.transactions)
  return &transactions_;
}
inline const ::bitcoin::Transaction& Block::_internal_transactions(int index) const {
  return transactions_.Get(index);
}
inline const ::bitcoin::Transaction& Block::transactions(int index) const {
  // @@protoc_insertion_point(field_get:bitcoin.Block.transactions)
  return _internal_transactions(index);
}
inline ::bitcoin::Transaction* Block::_internal_add_transactions() {
  return transactions_.Add();
}
inline ::bitcoin::Transaction* Block::add_transactions() {
  ::bitcoin::Transaction* _add = _internal_add_transactions();
  // @@protoc_insertion_point(field_add:bitcoin.Block.transactions)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Transaction >&
Block::transactions() const {
  // @@protoc_insertion_point(field_list:bitcoin.Block.transactions)
  return transactions_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bitcoin

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_block_2eproto
