#ifndef GRPC_SERVER_H
#define GRPC_SERVER_H

#include <string>
#include <memory>

// These headers will be generated by protoc from our .proto files
#include "node_service.grpc.pb.h"
#include "node_service.pb.h"
#include "transaction.pb.h"
#include "block.pb.h"
#include "node.h"

#include <grpcpp/grpcpp.h>

/*
 * NodeServiceImpl
 *
 * Implements the gRPC service defined in node_service.proto.
 * Each node runs one of these servers to listen for incoming RPCs
 * (transactions, blocks, sync requests) from other nodes.
 *
 * Delegates all actual logic to the Node class.
 */

class NodeServiceImpl final : public bitcoin::NodeService::Service {
public:
    // Takes a reference to the Node that owns this server
    NodeServiceImpl(Node& node);

    // RPC: receive a transaction from a wallet or another node
    grpc::Status BroadcastTransaction(
        grpc::ServerContext* context,
        const bitcoin::BroadcastTransactionRequest* request,
        bitcoin::BroadcastTransactionResponse* response) override;

    // RPC: receive a mined block from another node
    grpc::Status BroadcastBlock(
        grpc::ServerContext* context,
        const bitcoin::BroadcastBlockRequest* request,
        bitcoin::BroadcastBlockResponse* response) override;

    // RPC: a new node requests the blockchain to sync up
    grpc::Status GetBlockchain(
        grpc::ServerContext* context,
        const bitcoin::GetBlockchainRequest* request,
        bitcoin::GetBlockchainResponse* response) override;

    // RPC: check if a transaction has been confirmed in a block
    grpc::Status GetTransactionStatus(
        grpc::ServerContext* context,
        const bitcoin::GetTransactionStatusRequest* request,
        bitcoin::GetTransactionStatusResponse* response) override;

private:
    Node& node_;   // reference to the node that handles the actual logic

    // Convert between protobuf messages and our C++ structs
    GeneratedTransaction proto_to_transaction(const bitcoin::Transaction& proto_tx);
    bitcoin::Transaction transaction_to_proto(const GeneratedTransaction& tx);
    BlockData proto_to_block(const bitcoin::Block& proto_block);
    bitcoin::Block block_to_proto(const BlockData& block);
};

// Helper: starts the gRPC server on the given address
void run_grpc_server(Node& node, const std::string& address);

#endif // GRPC_SERVER_H
