#ifndef GRPC_SERVER_H
#define GRPC_SERVER_H

#include <string>
#include <memory>
#include <grpcpp/grpcpp.h>

// These headers are generated by protoc from our .proto files
#include "node_service.grpc.pb.h"
#include "node_service.pb.h"
#include "transaction.pb.h"
#include "block.pb.h"

#include "node.h"

// Implements the gRPC service defined in node_service.proto.
// Each node runs one of these servers to listen for incoming RPCs.
// Delegates all actual logic to the Node class.

class NodeServiceImpl final : public bitcoin::NodeService::Service {
public:
  NodeServiceImpl(Node& node);

  grpc::Status BroadcastTransaction(
      grpc::ServerContext* context,
      const bitcoin::BroadcastTransactionRequest* request,
      bitcoin::BroadcastTransactionResponse* response) override;

  grpc::Status BroadcastBlock(
      grpc::ServerContext* context,
      const bitcoin::BroadcastBlockRequest* request,
      bitcoin::BroadcastBlockResponse* response) override;

  grpc::Status GetBlockchain(
      grpc::ServerContext* context,
      const bitcoin::GetBlockchainRequest* request,
      bitcoin::GetBlockchainResponse* response) override;

  grpc::Status GetTransactionStatus(
      grpc::ServerContext* context,
      const bitcoin::GetTransactionStatusRequest* request,
      bitcoin::GetTransactionStatusResponse* response) override;

private:
  Node& node_;

  // Conversion between protobuf messages and our C++ structs
  GeneratedTransaction proto_to_transaction(const bitcoin::Transaction& proto_tx);
  bitcoin::Transaction transaction_to_proto(const GeneratedTransaction& tx);
  BlockData proto_to_block(const bitcoin::Block& proto_block);
  bitcoin::Block block_to_proto(const BlockData& block);
};

// Starts the gRPC server on the given address (blocks forever)
void run_grpc_server(Node& node, const std::string& address);

#endif // GRPC_SERVER_H
