// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node_service.proto

#include "node_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace bitcoin {
PROTOBUF_CONSTEXPR BroadcastTransactionRequest::BroadcastTransactionRequest(
    ::_pbi::ConstantInitialized)
  : transaction_(nullptr){}
struct BroadcastTransactionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastTransactionRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastTransactionRequestDefaultTypeInternal() {}
  union {
    BroadcastTransactionRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastTransactionRequestDefaultTypeInternal _BroadcastTransactionRequest_default_instance_;
PROTOBUF_CONSTEXPR BroadcastTransactionResponse::BroadcastTransactionResponse(
    ::_pbi::ConstantInitialized)
  : message_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , node_id_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , accepted_(false){}
struct BroadcastTransactionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastTransactionResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastTransactionResponseDefaultTypeInternal() {}
  union {
    BroadcastTransactionResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastTransactionResponseDefaultTypeInternal _BroadcastTransactionResponse_default_instance_;
PROTOBUF_CONSTEXPR BroadcastBlockRequest::BroadcastBlockRequest(
    ::_pbi::ConstantInitialized)
  : block_(nullptr){}
struct BroadcastBlockRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastBlockRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastBlockRequestDefaultTypeInternal() {}
  union {
    BroadcastBlockRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastBlockRequestDefaultTypeInternal _BroadcastBlockRequest_default_instance_;
PROTOBUF_CONSTEXPR BroadcastBlockResponse::BroadcastBlockResponse(
    ::_pbi::ConstantInitialized)
  : message_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , node_id_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , accepted_(false){}
struct BroadcastBlockResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BroadcastBlockResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BroadcastBlockResponseDefaultTypeInternal() {}
  union {
    BroadcastBlockResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BroadcastBlockResponseDefaultTypeInternal _BroadcastBlockResponse_default_instance_;
PROTOBUF_CONSTEXPR GetBlockchainRequest::GetBlockchainRequest(
    ::_pbi::ConstantInitialized)
  : start_index_(uint64_t{0u}){}
struct GetBlockchainRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBlockchainRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBlockchainRequestDefaultTypeInternal() {}
  union {
    GetBlockchainRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBlockchainRequestDefaultTypeInternal _GetBlockchainRequest_default_instance_;
PROTOBUF_CONSTEXPR GetBlockchainResponse::GetBlockchainResponse(
    ::_pbi::ConstantInitialized)
  : blocks_(){}
struct GetBlockchainResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetBlockchainResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetBlockchainResponseDefaultTypeInternal() {}
  union {
    GetBlockchainResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetBlockchainResponseDefaultTypeInternal _GetBlockchainResponse_default_instance_;
PROTOBUF_CONSTEXPR GetTransactionStatusRequest::GetTransactionStatusRequest(
    ::_pbi::ConstantInitialized)
  : transaction_id_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}){}
struct GetTransactionStatusRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetTransactionStatusRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetTransactionStatusRequestDefaultTypeInternal() {}
  union {
    GetTransactionStatusRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetTransactionStatusRequestDefaultTypeInternal _GetTransactionStatusRequest_default_instance_;
PROTOBUF_CONSTEXPR GetTransactionStatusResponse::GetTransactionStatusResponse(
    ::_pbi::ConstantInitialized)
  : block_hash_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , node_id_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , confirmed_(false){}
struct GetTransactionStatusResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetTransactionStatusResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetTransactionStatusResponseDefaultTypeInternal() {}
  union {
    GetTransactionStatusResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetTransactionStatusResponseDefaultTypeInternal _GetTransactionStatusResponse_default_instance_;
}  // namespace bitcoin
static ::_pb::Metadata file_level_metadata_node_5fservice_2eproto[8];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_node_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_node_5fservice_2eproto = nullptr;

const uint32_t TableStruct_node_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastTransactionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastTransactionRequest, transaction_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastTransactionResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastTransactionResponse, accepted_),
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastTransactionResponse, message_),
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastTransactionResponse, node_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastBlockRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastBlockRequest, block_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastBlockResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastBlockResponse, accepted_),
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastBlockResponse, message_),
  PROTOBUF_FIELD_OFFSET(::bitcoin::BroadcastBlockResponse, node_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetBlockchainRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetBlockchainRequest, start_index_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetBlockchainResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetBlockchainResponse, blocks_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetTransactionStatusRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetTransactionStatusRequest, transaction_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetTransactionStatusResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetTransactionStatusResponse, confirmed_),
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetTransactionStatusResponse, block_hash_),
  PROTOBUF_FIELD_OFFSET(::bitcoin::GetTransactionStatusResponse, node_id_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::bitcoin::BroadcastTransactionRequest)},
  { 7, -1, -1, sizeof(::bitcoin::BroadcastTransactionResponse)},
  { 16, -1, -1, sizeof(::bitcoin::BroadcastBlockRequest)},
  { 23, -1, -1, sizeof(::bitcoin::BroadcastBlockResponse)},
  { 32, -1, -1, sizeof(::bitcoin::GetBlockchainRequest)},
  { 39, -1, -1, sizeof(::bitcoin::GetBlockchainResponse)},
  { 46, -1, -1, sizeof(::bitcoin::GetTransactionStatusRequest)},
  { 53, -1, -1, sizeof(::bitcoin::GetTransactionStatusResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::bitcoin::_BroadcastTransactionRequest_default_instance_._instance,
  &::bitcoin::_BroadcastTransactionResponse_default_instance_._instance,
  &::bitcoin::_BroadcastBlockRequest_default_instance_._instance,
  &::bitcoin::_BroadcastBlockResponse_default_instance_._instance,
  &::bitcoin::_GetBlockchainRequest_default_instance_._instance,
  &::bitcoin::_GetBlockchainResponse_default_instance_._instance,
  &::bitcoin::_GetTransactionStatusRequest_default_instance_._instance,
  &::bitcoin::_GetTransactionStatusResponse_default_instance_._instance,
};

const char descriptor_table_protodef_node_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022node_service.proto\022\007bitcoin\032\021transacti"
  "on.proto\032\013block.proto\032\nnode.proto\"H\n\033Bro"
  "adcastTransactionRequest\022)\n\013transaction\030"
  "\001 \001(\0132\024.bitcoin.Transaction\"R\n\034Broadcast"
  "TransactionResponse\022\020\n\010accepted\030\001 \001(\010\022\017\n"
  "\007message\030\002 \001(\t\022\017\n\007node_id\030\003 \001(\t\"6\n\025Broad"
  "castBlockRequest\022\035\n\005block\030\001 \001(\0132\016.bitcoi"
  "n.Block\"L\n\026BroadcastBlockResponse\022\020\n\010acc"
  "epted\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\017\n\007node_id\030"
  "\003 \001(\t\"+\n\024GetBlockchainRequest\022\023\n\013start_i"
  "ndex\030\001 \001(\004\"7\n\025GetBlockchainResponse\022\036\n\006b"
  "locks\030\001 \003(\0132\016.bitcoin.Block\"5\n\033GetTransa"
  "ctionStatusRequest\022\026\n\016transaction_id\030\001 \001"
  "(\014\"V\n\034GetTransactionStatusResponse\022\021\n\tco"
  "nfirmed\030\001 \001(\010\022\022\n\nblock_hash\030\002 \001(\014\022\017\n\007nod"
  "e_id\030\003 \001(\t2\372\002\n\013NodeService\022c\n\024BroadcastT"
  "ransaction\022$.bitcoin.BroadcastTransactio"
  "nRequest\032%.bitcoin.BroadcastTransactionR"
  "esponse\022Q\n\016BroadcastBlock\022\036.bitcoin.Broa"
  "dcastBlockRequest\032\037.bitcoin.BroadcastBlo"
  "ckResponse\022N\n\rGetBlockchain\022\035.bitcoin.Ge"
  "tBlockchainRequest\032\036.bitcoin.GetBlockcha"
  "inResponse\022c\n\024GetTransactionStatus\022$.bit"
  "coin.GetTransactionStatusRequest\032%.bitco"
  "in.GetTransactionStatusResponseb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_node_5fservice_2eproto_deps[3] = {
  &::descriptor_table_block_2eproto,
  &::descriptor_table_node_2eproto,
  &::descriptor_table_transaction_2eproto,
};
static ::_pbi::once_flag descriptor_table_node_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_node_5fservice_2eproto = {
    false, false, 999, descriptor_table_protodef_node_5fservice_2eproto,
    "node_service.proto",
    &descriptor_table_node_5fservice_2eproto_once, descriptor_table_node_5fservice_2eproto_deps, 3, 8,
    schemas, file_default_instances, TableStruct_node_5fservice_2eproto::offsets,
    file_level_metadata_node_5fservice_2eproto, file_level_enum_descriptors_node_5fservice_2eproto,
    file_level_service_descriptors_node_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_node_5fservice_2eproto_getter() {
  return &descriptor_table_node_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_node_5fservice_2eproto(&descriptor_table_node_5fservice_2eproto);
namespace bitcoin {

// ===================================================================

class BroadcastTransactionRequest::_Internal {
 public:
  static const ::bitcoin::Transaction& transaction(const BroadcastTransactionRequest* msg);
};

const ::bitcoin::Transaction&
BroadcastTransactionRequest::_Internal::transaction(const BroadcastTransactionRequest* msg) {
  return *msg->transaction_;
}
void BroadcastTransactionRequest::clear_transaction() {
  if (GetArenaForAllocation() == nullptr && transaction_ != nullptr) {
    delete transaction_;
  }
  transaction_ = nullptr;
}
BroadcastTransactionRequest::BroadcastTransactionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:bitcoin.BroadcastTransactionRequest)
}
BroadcastTransactionRequest::BroadcastTransactionRequest(const BroadcastTransactionRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_transaction()) {
    transaction_ = new ::bitcoin::Transaction(*from.transaction_);
  } else {
    transaction_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:bitcoin.BroadcastTransactionRequest)
}

inline void BroadcastTransactionRequest::SharedCtor() {
transaction_ = nullptr;
}

BroadcastTransactionRequest::~BroadcastTransactionRequest() {
  // @@protoc_insertion_point(destructor:bitcoin.BroadcastTransactionRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BroadcastTransactionRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete transaction_;
}

void BroadcastTransactionRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BroadcastTransactionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:bitcoin.BroadcastTransactionRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && transaction_ != nullptr) {
    delete transaction_;
  }
  transaction_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BroadcastTransactionRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .bitcoin.Transaction transaction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_transaction(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BroadcastTransactionRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bitcoin.BroadcastTransactionRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .bitcoin.Transaction transaction = 1;
  if (this->_internal_has_transaction()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::transaction(this),
        _Internal::transaction(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bitcoin.BroadcastTransactionRequest)
  return target;
}

size_t BroadcastTransactionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bitcoin.BroadcastTransactionRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .bitcoin.Transaction transaction = 1;
  if (this->_internal_has_transaction()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *transaction_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BroadcastTransactionRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BroadcastTransactionRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BroadcastTransactionRequest::GetClassData() const { return &_class_data_; }

void BroadcastTransactionRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BroadcastTransactionRequest *>(to)->MergeFrom(
      static_cast<const BroadcastTransactionRequest &>(from));
}


void BroadcastTransactionRequest::MergeFrom(const BroadcastTransactionRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bitcoin.BroadcastTransactionRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_transaction()) {
    _internal_mutable_transaction()->::bitcoin::Transaction::MergeFrom(from._internal_transaction());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastTransactionRequest::CopyFrom(const BroadcastTransactionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitcoin.BroadcastTransactionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BroadcastTransactionRequest::IsInitialized() const {
  return true;
}

void BroadcastTransactionRequest::InternalSwap(BroadcastTransactionRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(transaction_, other->transaction_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BroadcastTransactionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_5fservice_2eproto_getter, &descriptor_table_node_5fservice_2eproto_once,
      file_level_metadata_node_5fservice_2eproto[0]);
}

// ===================================================================

class BroadcastTransactionResponse::_Internal {
 public:
};

BroadcastTransactionResponse::BroadcastTransactionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:bitcoin.BroadcastTransactionResponse)
}
BroadcastTransactionResponse::BroadcastTransactionResponse(const BroadcastTransactionResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    message_.Set(from._internal_message(), 
      GetArenaForAllocation());
  }
  node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_node_id().empty()) {
    node_id_.Set(from._internal_node_id(), 
      GetArenaForAllocation());
  }
  accepted_ = from.accepted_;
  // @@protoc_insertion_point(copy_constructor:bitcoin.BroadcastTransactionResponse)
}

inline void BroadcastTransactionResponse::SharedCtor() {
message_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  message_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
node_id_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  node_id_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
accepted_ = false;
}

BroadcastTransactionResponse::~BroadcastTransactionResponse() {
  // @@protoc_insertion_point(destructor:bitcoin.BroadcastTransactionResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BroadcastTransactionResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  message_.Destroy();
  node_id_.Destroy();
}

void BroadcastTransactionResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BroadcastTransactionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:bitcoin.BroadcastTransactionResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmpty();
  node_id_.ClearToEmpty();
  accepted_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BroadcastTransactionResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool accepted = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          accepted_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "bitcoin.BroadcastTransactionResponse.message"));
        } else
          goto handle_unusual;
        continue;
      // string node_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_node_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "bitcoin.BroadcastTransactionResponse.node_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BroadcastTransactionResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bitcoin.BroadcastTransactionResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool accepted = 1;
  if (this->_internal_accepted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_accepted(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bitcoin.BroadcastTransactionResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  // string node_id = 3;
  if (!this->_internal_node_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_node_id().data(), static_cast<int>(this->_internal_node_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bitcoin.BroadcastTransactionResponse.node_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_node_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bitcoin.BroadcastTransactionResponse)
  return target;
}

size_t BroadcastTransactionResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bitcoin.BroadcastTransactionResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // string node_id = 3;
  if (!this->_internal_node_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_node_id());
  }

  // bool accepted = 1;
  if (this->_internal_accepted() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BroadcastTransactionResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BroadcastTransactionResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BroadcastTransactionResponse::GetClassData() const { return &_class_data_; }

void BroadcastTransactionResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BroadcastTransactionResponse *>(to)->MergeFrom(
      static_cast<const BroadcastTransactionResponse &>(from));
}


void BroadcastTransactionResponse::MergeFrom(const BroadcastTransactionResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bitcoin.BroadcastTransactionResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _internal_set_message(from._internal_message());
  }
  if (!from._internal_node_id().empty()) {
    _internal_set_node_id(from._internal_node_id());
  }
  if (from._internal_accepted() != 0) {
    _internal_set_accepted(from._internal_accepted());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastTransactionResponse::CopyFrom(const BroadcastTransactionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitcoin.BroadcastTransactionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BroadcastTransactionResponse::IsInitialized() const {
  return true;
}

void BroadcastTransactionResponse::InternalSwap(BroadcastTransactionResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &message_, lhs_arena,
      &other->message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &node_id_, lhs_arena,
      &other->node_id_, rhs_arena
  );
  swap(accepted_, other->accepted_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BroadcastTransactionResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_5fservice_2eproto_getter, &descriptor_table_node_5fservice_2eproto_once,
      file_level_metadata_node_5fservice_2eproto[1]);
}

// ===================================================================

class BroadcastBlockRequest::_Internal {
 public:
  static const ::bitcoin::Block& block(const BroadcastBlockRequest* msg);
};

const ::bitcoin::Block&
BroadcastBlockRequest::_Internal::block(const BroadcastBlockRequest* msg) {
  return *msg->block_;
}
void BroadcastBlockRequest::clear_block() {
  if (GetArenaForAllocation() == nullptr && block_ != nullptr) {
    delete block_;
  }
  block_ = nullptr;
}
BroadcastBlockRequest::BroadcastBlockRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:bitcoin.BroadcastBlockRequest)
}
BroadcastBlockRequest::BroadcastBlockRequest(const BroadcastBlockRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_block()) {
    block_ = new ::bitcoin::Block(*from.block_);
  } else {
    block_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:bitcoin.BroadcastBlockRequest)
}

inline void BroadcastBlockRequest::SharedCtor() {
block_ = nullptr;
}

BroadcastBlockRequest::~BroadcastBlockRequest() {
  // @@protoc_insertion_point(destructor:bitcoin.BroadcastBlockRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BroadcastBlockRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete block_;
}

void BroadcastBlockRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BroadcastBlockRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:bitcoin.BroadcastBlockRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && block_ != nullptr) {
    delete block_;
  }
  block_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BroadcastBlockRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .bitcoin.Block block = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_block(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BroadcastBlockRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bitcoin.BroadcastBlockRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .bitcoin.Block block = 1;
  if (this->_internal_has_block()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::block(this),
        _Internal::block(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bitcoin.BroadcastBlockRequest)
  return target;
}

size_t BroadcastBlockRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bitcoin.BroadcastBlockRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .bitcoin.Block block = 1;
  if (this->_internal_has_block()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *block_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BroadcastBlockRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BroadcastBlockRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BroadcastBlockRequest::GetClassData() const { return &_class_data_; }

void BroadcastBlockRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BroadcastBlockRequest *>(to)->MergeFrom(
      static_cast<const BroadcastBlockRequest &>(from));
}


void BroadcastBlockRequest::MergeFrom(const BroadcastBlockRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bitcoin.BroadcastBlockRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_block()) {
    _internal_mutable_block()->::bitcoin::Block::MergeFrom(from._internal_block());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastBlockRequest::CopyFrom(const BroadcastBlockRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitcoin.BroadcastBlockRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BroadcastBlockRequest::IsInitialized() const {
  return true;
}

void BroadcastBlockRequest::InternalSwap(BroadcastBlockRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(block_, other->block_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BroadcastBlockRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_5fservice_2eproto_getter, &descriptor_table_node_5fservice_2eproto_once,
      file_level_metadata_node_5fservice_2eproto[2]);
}

// ===================================================================

class BroadcastBlockResponse::_Internal {
 public:
};

BroadcastBlockResponse::BroadcastBlockResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:bitcoin.BroadcastBlockResponse)
}
BroadcastBlockResponse::BroadcastBlockResponse(const BroadcastBlockResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    message_.Set(from._internal_message(), 
      GetArenaForAllocation());
  }
  node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_node_id().empty()) {
    node_id_.Set(from._internal_node_id(), 
      GetArenaForAllocation());
  }
  accepted_ = from.accepted_;
  // @@protoc_insertion_point(copy_constructor:bitcoin.BroadcastBlockResponse)
}

inline void BroadcastBlockResponse::SharedCtor() {
message_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  message_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
node_id_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  node_id_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
accepted_ = false;
}

BroadcastBlockResponse::~BroadcastBlockResponse() {
  // @@protoc_insertion_point(destructor:bitcoin.BroadcastBlockResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BroadcastBlockResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  message_.Destroy();
  node_id_.Destroy();
}

void BroadcastBlockResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void BroadcastBlockResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:bitcoin.BroadcastBlockResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmpty();
  node_id_.ClearToEmpty();
  accepted_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BroadcastBlockResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool accepted = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          accepted_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "bitcoin.BroadcastBlockResponse.message"));
        } else
          goto handle_unusual;
        continue;
      // string node_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_node_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "bitcoin.BroadcastBlockResponse.node_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BroadcastBlockResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bitcoin.BroadcastBlockResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool accepted = 1;
  if (this->_internal_accepted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_accepted(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bitcoin.BroadcastBlockResponse.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  // string node_id = 3;
  if (!this->_internal_node_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_node_id().data(), static_cast<int>(this->_internal_node_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bitcoin.BroadcastBlockResponse.node_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_node_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bitcoin.BroadcastBlockResponse)
  return target;
}

size_t BroadcastBlockResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bitcoin.BroadcastBlockResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // string node_id = 3;
  if (!this->_internal_node_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_node_id());
  }

  // bool accepted = 1;
  if (this->_internal_accepted() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BroadcastBlockResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    BroadcastBlockResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BroadcastBlockResponse::GetClassData() const { return &_class_data_; }

void BroadcastBlockResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<BroadcastBlockResponse *>(to)->MergeFrom(
      static_cast<const BroadcastBlockResponse &>(from));
}


void BroadcastBlockResponse::MergeFrom(const BroadcastBlockResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bitcoin.BroadcastBlockResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _internal_set_message(from._internal_message());
  }
  if (!from._internal_node_id().empty()) {
    _internal_set_node_id(from._internal_node_id());
  }
  if (from._internal_accepted() != 0) {
    _internal_set_accepted(from._internal_accepted());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BroadcastBlockResponse::CopyFrom(const BroadcastBlockResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitcoin.BroadcastBlockResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BroadcastBlockResponse::IsInitialized() const {
  return true;
}

void BroadcastBlockResponse::InternalSwap(BroadcastBlockResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &message_, lhs_arena,
      &other->message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &node_id_, lhs_arena,
      &other->node_id_, rhs_arena
  );
  swap(accepted_, other->accepted_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BroadcastBlockResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_5fservice_2eproto_getter, &descriptor_table_node_5fservice_2eproto_once,
      file_level_metadata_node_5fservice_2eproto[3]);
}

// ===================================================================

class GetBlockchainRequest::_Internal {
 public:
};

GetBlockchainRequest::GetBlockchainRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:bitcoin.GetBlockchainRequest)
}
GetBlockchainRequest::GetBlockchainRequest(const GetBlockchainRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  start_index_ = from.start_index_;
  // @@protoc_insertion_point(copy_constructor:bitcoin.GetBlockchainRequest)
}

inline void GetBlockchainRequest::SharedCtor() {
start_index_ = uint64_t{0u};
}

GetBlockchainRequest::~GetBlockchainRequest() {
  // @@protoc_insertion_point(destructor:bitcoin.GetBlockchainRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetBlockchainRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetBlockchainRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void GetBlockchainRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:bitcoin.GetBlockchainRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  start_index_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetBlockchainRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 start_index = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          start_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetBlockchainRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bitcoin.GetBlockchainRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 start_index = 1;
  if (this->_internal_start_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_start_index(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bitcoin.GetBlockchainRequest)
  return target;
}

size_t GetBlockchainRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bitcoin.GetBlockchainRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 start_index = 1;
  if (this->_internal_start_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_start_index());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetBlockchainRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    GetBlockchainRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetBlockchainRequest::GetClassData() const { return &_class_data_; }

void GetBlockchainRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<GetBlockchainRequest *>(to)->MergeFrom(
      static_cast<const GetBlockchainRequest &>(from));
}


void GetBlockchainRequest::MergeFrom(const GetBlockchainRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bitcoin.GetBlockchainRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_start_index() != 0) {
    _internal_set_start_index(from._internal_start_index());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetBlockchainRequest::CopyFrom(const GetBlockchainRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitcoin.GetBlockchainRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetBlockchainRequest::IsInitialized() const {
  return true;
}

void GetBlockchainRequest::InternalSwap(GetBlockchainRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(start_index_, other->start_index_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetBlockchainRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_5fservice_2eproto_getter, &descriptor_table_node_5fservice_2eproto_once,
      file_level_metadata_node_5fservice_2eproto[4]);
}

// ===================================================================

class GetBlockchainResponse::_Internal {
 public:
};

void GetBlockchainResponse::clear_blocks() {
  blocks_.Clear();
}
GetBlockchainResponse::GetBlockchainResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  blocks_(arena) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:bitcoin.GetBlockchainResponse)
}
GetBlockchainResponse::GetBlockchainResponse(const GetBlockchainResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      blocks_(from.blocks_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:bitcoin.GetBlockchainResponse)
}

inline void GetBlockchainResponse::SharedCtor() {
}

GetBlockchainResponse::~GetBlockchainResponse() {
  // @@protoc_insertion_point(destructor:bitcoin.GetBlockchainResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetBlockchainResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GetBlockchainResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void GetBlockchainResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:bitcoin.GetBlockchainResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  blocks_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetBlockchainResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .bitcoin.Block blocks = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_blocks(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetBlockchainResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bitcoin.GetBlockchainResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .bitcoin.Block blocks = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_blocks_size()); i < n; i++) {
    const auto& repfield = this->_internal_blocks(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bitcoin.GetBlockchainResponse)
  return target;
}

size_t GetBlockchainResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bitcoin.GetBlockchainResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .bitcoin.Block blocks = 1;
  total_size += 1UL * this->_internal_blocks_size();
  for (const auto& msg : this->blocks_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetBlockchainResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    GetBlockchainResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetBlockchainResponse::GetClassData() const { return &_class_data_; }

void GetBlockchainResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<GetBlockchainResponse *>(to)->MergeFrom(
      static_cast<const GetBlockchainResponse &>(from));
}


void GetBlockchainResponse::MergeFrom(const GetBlockchainResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bitcoin.GetBlockchainResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  blocks_.MergeFrom(from.blocks_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetBlockchainResponse::CopyFrom(const GetBlockchainResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitcoin.GetBlockchainResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetBlockchainResponse::IsInitialized() const {
  return true;
}

void GetBlockchainResponse::InternalSwap(GetBlockchainResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  blocks_.InternalSwap(&other->blocks_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetBlockchainResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_5fservice_2eproto_getter, &descriptor_table_node_5fservice_2eproto_once,
      file_level_metadata_node_5fservice_2eproto[5]);
}

// ===================================================================

class GetTransactionStatusRequest::_Internal {
 public:
};

GetTransactionStatusRequest::GetTransactionStatusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:bitcoin.GetTransactionStatusRequest)
}
GetTransactionStatusRequest::GetTransactionStatusRequest(const GetTransactionStatusRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  transaction_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    transaction_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_transaction_id().empty()) {
    transaction_id_.Set(from._internal_transaction_id(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:bitcoin.GetTransactionStatusRequest)
}

inline void GetTransactionStatusRequest::SharedCtor() {
transaction_id_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  transaction_id_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

GetTransactionStatusRequest::~GetTransactionStatusRequest() {
  // @@protoc_insertion_point(destructor:bitcoin.GetTransactionStatusRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetTransactionStatusRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  transaction_id_.Destroy();
}

void GetTransactionStatusRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void GetTransactionStatusRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:bitcoin.GetTransactionStatusRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  transaction_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetTransactionStatusRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes transaction_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_transaction_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetTransactionStatusRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bitcoin.GetTransactionStatusRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes transaction_id = 1;
  if (!this->_internal_transaction_id().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_transaction_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bitcoin.GetTransactionStatusRequest)
  return target;
}

size_t GetTransactionStatusRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bitcoin.GetTransactionStatusRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes transaction_id = 1;
  if (!this->_internal_transaction_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_transaction_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetTransactionStatusRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    GetTransactionStatusRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetTransactionStatusRequest::GetClassData() const { return &_class_data_; }

void GetTransactionStatusRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<GetTransactionStatusRequest *>(to)->MergeFrom(
      static_cast<const GetTransactionStatusRequest &>(from));
}


void GetTransactionStatusRequest::MergeFrom(const GetTransactionStatusRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bitcoin.GetTransactionStatusRequest)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_transaction_id().empty()) {
    _internal_set_transaction_id(from._internal_transaction_id());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetTransactionStatusRequest::CopyFrom(const GetTransactionStatusRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitcoin.GetTransactionStatusRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetTransactionStatusRequest::IsInitialized() const {
  return true;
}

void GetTransactionStatusRequest::InternalSwap(GetTransactionStatusRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &transaction_id_, lhs_arena,
      &other->transaction_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata GetTransactionStatusRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_5fservice_2eproto_getter, &descriptor_table_node_5fservice_2eproto_once,
      file_level_metadata_node_5fservice_2eproto[6]);
}

// ===================================================================

class GetTransactionStatusResponse::_Internal {
 public:
};

GetTransactionStatusResponse::GetTransactionStatusResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:bitcoin.GetTransactionStatusResponse)
}
GetTransactionStatusResponse::GetTransactionStatusResponse(const GetTransactionStatusResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  block_hash_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    block_hash_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_block_hash().empty()) {
    block_hash_.Set(from._internal_block_hash(), 
      GetArenaForAllocation());
  }
  node_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    node_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_node_id().empty()) {
    node_id_.Set(from._internal_node_id(), 
      GetArenaForAllocation());
  }
  confirmed_ = from.confirmed_;
  // @@protoc_insertion_point(copy_constructor:bitcoin.GetTransactionStatusResponse)
}

inline void GetTransactionStatusResponse::SharedCtor() {
block_hash_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  block_hash_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
node_id_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  node_id_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
confirmed_ = false;
}

GetTransactionStatusResponse::~GetTransactionStatusResponse() {
  // @@protoc_insertion_point(destructor:bitcoin.GetTransactionStatusResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetTransactionStatusResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  block_hash_.Destroy();
  node_id_.Destroy();
}

void GetTransactionStatusResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void GetTransactionStatusResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:bitcoin.GetTransactionStatusResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  block_hash_.ClearToEmpty();
  node_id_.ClearToEmpty();
  confirmed_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetTransactionStatusResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool confirmed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          confirmed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes block_hash = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_block_hash();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string node_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_node_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "bitcoin.GetTransactionStatusResponse.node_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetTransactionStatusResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bitcoin.GetTransactionStatusResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool confirmed = 1;
  if (this->_internal_confirmed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_confirmed(), target);
  }

  // bytes block_hash = 2;
  if (!this->_internal_block_hash().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_block_hash(), target);
  }

  // string node_id = 3;
  if (!this->_internal_node_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_node_id().data(), static_cast<int>(this->_internal_node_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "bitcoin.GetTransactionStatusResponse.node_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_node_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bitcoin.GetTransactionStatusResponse)
  return target;
}

size_t GetTransactionStatusResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bitcoin.GetTransactionStatusResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes block_hash = 2;
  if (!this->_internal_block_hash().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_block_hash());
  }

  // string node_id = 3;
  if (!this->_internal_node_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_node_id());
  }

  // bool confirmed = 1;
  if (this->_internal_confirmed() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetTransactionStatusResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    GetTransactionStatusResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetTransactionStatusResponse::GetClassData() const { return &_class_data_; }

void GetTransactionStatusResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<GetTransactionStatusResponse *>(to)->MergeFrom(
      static_cast<const GetTransactionStatusResponse &>(from));
}


void GetTransactionStatusResponse::MergeFrom(const GetTransactionStatusResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bitcoin.GetTransactionStatusResponse)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_block_hash().empty()) {
    _internal_set_block_hash(from._internal_block_hash());
  }
  if (!from._internal_node_id().empty()) {
    _internal_set_node_id(from._internal_node_id());
  }
  if (from._internal_confirmed() != 0) {
    _internal_set_confirmed(from._internal_confirmed());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetTransactionStatusResponse::CopyFrom(const GetTransactionStatusResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitcoin.GetTransactionStatusResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetTransactionStatusResponse::IsInitialized() const {
  return true;
}

void GetTransactionStatusResponse::InternalSwap(GetTransactionStatusResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &block_hash_, lhs_arena,
      &other->block_hash_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &node_id_, lhs_arena,
      &other->node_id_, rhs_arena
  );
  swap(confirmed_, other->confirmed_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetTransactionStatusResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_node_5fservice_2eproto_getter, &descriptor_table_node_5fservice_2eproto_once,
      file_level_metadata_node_5fservice_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace bitcoin
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::bitcoin::BroadcastTransactionRequest*
Arena::CreateMaybeMessage< ::bitcoin::BroadcastTransactionRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bitcoin::BroadcastTransactionRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::bitcoin::BroadcastTransactionResponse*
Arena::CreateMaybeMessage< ::bitcoin::BroadcastTransactionResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bitcoin::BroadcastTransactionResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::bitcoin::BroadcastBlockRequest*
Arena::CreateMaybeMessage< ::bitcoin::BroadcastBlockRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bitcoin::BroadcastBlockRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::bitcoin::BroadcastBlockResponse*
Arena::CreateMaybeMessage< ::bitcoin::BroadcastBlockResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bitcoin::BroadcastBlockResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::bitcoin::GetBlockchainRequest*
Arena::CreateMaybeMessage< ::bitcoin::GetBlockchainRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bitcoin::GetBlockchainRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::bitcoin::GetBlockchainResponse*
Arena::CreateMaybeMessage< ::bitcoin::GetBlockchainResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bitcoin::GetBlockchainResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::bitcoin::GetTransactionStatusRequest*
Arena::CreateMaybeMessage< ::bitcoin::GetTransactionStatusRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bitcoin::GetTransactionStatusRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::bitcoin::GetTransactionStatusResponse*
Arena::CreateMaybeMessage< ::bitcoin::GetTransactionStatusResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::bitcoin::GetTransactionStatusResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
