// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node_service.proto
// Original file comments:
// node_service.proto
//
#ifndef GRPC_node_5fservice_2eproto__INCLUDED
#define GRPC_node_5fservice_2eproto__INCLUDED

#include "node_service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace bitcoin {

// The gRPC service — function signatures that C++ will implement
//
class NodeService final {
 public:
  static constexpr char const* service_full_name() {
    return "bitcoin.NodeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // A wallet or node sends a new transaction to this node
    virtual ::grpc::Status BroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::bitcoin::BroadcastTransactionResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastTransactionResponse>> AsyncBroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastTransactionResponse>>(AsyncBroadcastTransactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastTransactionResponse>> PrepareAsyncBroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastTransactionResponse>>(PrepareAsyncBroadcastTransactionRaw(context, request, cq));
    }
    // A miner broadcasts a newly mined block to this node
    virtual ::grpc::Status BroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::bitcoin::BroadcastBlockResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastBlockResponse>> AsyncBroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastBlockResponse>>(AsyncBroadcastBlockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastBlockResponse>> PrepareAsyncBroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastBlockResponse>>(PrepareAsyncBroadcastBlockRaw(context, request, cq));
    }
    // A new node requests the full (or partial) blockchain to sync up
    virtual ::grpc::Status GetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::bitcoin::GetBlockchainResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetBlockchainResponse>> AsyncGetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetBlockchainResponse>>(AsyncGetBlockchainRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetBlockchainResponse>> PrepareAsyncGetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetBlockchainResponse>>(PrepareAsyncGetBlockchainRaw(context, request, cq));
    }
    // Query whether a transaction has been confirmed in a block
    virtual ::grpc::Status GetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::bitcoin::GetTransactionStatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetTransactionStatusResponse>> AsyncGetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetTransactionStatusResponse>>(AsyncGetTransactionStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetTransactionStatusResponse>> PrepareAsyncGetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetTransactionStatusResponse>>(PrepareAsyncGetTransactionStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // A wallet or node sends a new transaction to this node
      virtual void BroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest* request, ::bitcoin::BroadcastTransactionResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void BroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest* request, ::bitcoin::BroadcastTransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // A miner broadcasts a newly mined block to this node
      virtual void BroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest* request, ::bitcoin::BroadcastBlockResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void BroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest* request, ::bitcoin::BroadcastBlockResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // A new node requests the full (or partial) blockchain to sync up
      virtual void GetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest* request, ::bitcoin::GetBlockchainResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest* request, ::bitcoin::GetBlockchainResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Query whether a transaction has been confirmed in a block
      virtual void GetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest* request, ::bitcoin::GetTransactionStatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest* request, ::bitcoin::GetTransactionStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastTransactionResponse>* AsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastTransactionResponse>* PrepareAsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastBlockResponse>* AsyncBroadcastBlockRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::BroadcastBlockResponse>* PrepareAsyncBroadcastBlockRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetBlockchainResponse>* AsyncGetBlockchainRaw(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetBlockchainResponse>* PrepareAsyncGetBlockchainRaw(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetTransactionStatusResponse>* AsyncGetTransactionStatusRaw(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bitcoin::GetTransactionStatusResponse>* PrepareAsyncGetTransactionStatusRaw(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status BroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::bitcoin::BroadcastTransactionResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastTransactionResponse>> AsyncBroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastTransactionResponse>>(AsyncBroadcastTransactionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastTransactionResponse>> PrepareAsyncBroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastTransactionResponse>>(PrepareAsyncBroadcastTransactionRaw(context, request, cq));
    }
    ::grpc::Status BroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::bitcoin::BroadcastBlockResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastBlockResponse>> AsyncBroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastBlockResponse>>(AsyncBroadcastBlockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastBlockResponse>> PrepareAsyncBroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastBlockResponse>>(PrepareAsyncBroadcastBlockRaw(context, request, cq));
    }
    ::grpc::Status GetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::bitcoin::GetBlockchainResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::GetBlockchainResponse>> AsyncGetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::GetBlockchainResponse>>(AsyncGetBlockchainRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::GetBlockchainResponse>> PrepareAsyncGetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::GetBlockchainResponse>>(PrepareAsyncGetBlockchainRaw(context, request, cq));
    }
    ::grpc::Status GetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::bitcoin::GetTransactionStatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::GetTransactionStatusResponse>> AsyncGetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::GetTransactionStatusResponse>>(AsyncGetTransactionStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::GetTransactionStatusResponse>> PrepareAsyncGetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bitcoin::GetTransactionStatusResponse>>(PrepareAsyncGetTransactionStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void BroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest* request, ::bitcoin::BroadcastTransactionResponse* response, std::function<void(::grpc::Status)>) override;
      void BroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest* request, ::bitcoin::BroadcastTransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void BroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest* request, ::bitcoin::BroadcastBlockResponse* response, std::function<void(::grpc::Status)>) override;
      void BroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest* request, ::bitcoin::BroadcastBlockResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest* request, ::bitcoin::GetBlockchainResponse* response, std::function<void(::grpc::Status)>) override;
      void GetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest* request, ::bitcoin::GetBlockchainResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest* request, ::bitcoin::GetTransactionStatusResponse* response, std::function<void(::grpc::Status)>) override;
      void GetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest* request, ::bitcoin::GetTransactionStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastTransactionResponse>* AsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastTransactionResponse>* PrepareAsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastBlockResponse>* AsyncBroadcastBlockRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastBlockResponse>* PrepareAsyncBroadcastBlockRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bitcoin::GetBlockchainResponse>* AsyncGetBlockchainRaw(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bitcoin::GetBlockchainResponse>* PrepareAsyncGetBlockchainRaw(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bitcoin::GetTransactionStatusResponse>* AsyncGetTransactionStatusRaw(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bitcoin::GetTransactionStatusResponse>* PrepareAsyncGetTransactionStatusRaw(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_BroadcastTransaction_;
    const ::grpc::internal::RpcMethod rpcmethod_BroadcastBlock_;
    const ::grpc::internal::RpcMethod rpcmethod_GetBlockchain_;
    const ::grpc::internal::RpcMethod rpcmethod_GetTransactionStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // A wallet or node sends a new transaction to this node
    virtual ::grpc::Status BroadcastTransaction(::grpc::ServerContext* context, const ::bitcoin::BroadcastTransactionRequest* request, ::bitcoin::BroadcastTransactionResponse* response);
    // A miner broadcasts a newly mined block to this node
    virtual ::grpc::Status BroadcastBlock(::grpc::ServerContext* context, const ::bitcoin::BroadcastBlockRequest* request, ::bitcoin::BroadcastBlockResponse* response);
    // A new node requests the full (or partial) blockchain to sync up
    virtual ::grpc::Status GetBlockchain(::grpc::ServerContext* context, const ::bitcoin::GetBlockchainRequest* request, ::bitcoin::GetBlockchainResponse* response);
    // Query whether a transaction has been confirmed in a block
    virtual ::grpc::Status GetTransactionStatus(::grpc::ServerContext* context, const ::bitcoin::GetTransactionStatusRequest* request, ::bitcoin::GetTransactionStatusResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastTransactionRequest* /*request*/, ::bitcoin::BroadcastTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBroadcastTransaction(::grpc::ServerContext* context, ::bitcoin::BroadcastTransactionRequest* request, ::grpc::ServerAsyncResponseWriter< ::bitcoin::BroadcastTransactionResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_BroadcastBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_BroadcastBlock() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_BroadcastBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastBlock(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastBlockRequest* /*request*/, ::bitcoin::BroadcastBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBroadcastBlock(::grpc::ServerContext* context, ::bitcoin::BroadcastBlockRequest* request, ::grpc::ServerAsyncResponseWriter< ::bitcoin::BroadcastBlockResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetBlockchain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetBlockchain() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetBlockchain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockchain(::grpc::ServerContext* /*context*/, const ::bitcoin::GetBlockchainRequest* /*request*/, ::bitcoin::GetBlockchainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBlockchain(::grpc::ServerContext* context, ::bitcoin::GetBlockchainRequest* request, ::grpc::ServerAsyncResponseWriter< ::bitcoin::GetBlockchainResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetTransactionStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetTransactionStatus() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetTransactionStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransactionStatus(::grpc::ServerContext* /*context*/, const ::bitcoin::GetTransactionStatusRequest* /*request*/, ::bitcoin::GetTransactionStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTransactionStatus(::grpc::ServerContext* context, ::bitcoin::GetTransactionStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::bitcoin::GetTransactionStatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_BroadcastTransaction<WithAsyncMethod_BroadcastBlock<WithAsyncMethod_GetBlockchain<WithAsyncMethod_GetTransactionStatus<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::bitcoin::BroadcastTransactionRequest, ::bitcoin::BroadcastTransactionResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bitcoin::BroadcastTransactionRequest* request, ::bitcoin::BroadcastTransactionResponse* response) { return this->BroadcastTransaction(context, request, response); }));}
    void SetMessageAllocatorFor_BroadcastTransaction(
        ::grpc::MessageAllocator< ::bitcoin::BroadcastTransactionRequest, ::bitcoin::BroadcastTransactionResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bitcoin::BroadcastTransactionRequest, ::bitcoin::BroadcastTransactionResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastTransactionRequest* /*request*/, ::bitcoin::BroadcastTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BroadcastTransaction(
      ::grpc::CallbackServerContext* /*context*/, const ::bitcoin::BroadcastTransactionRequest* /*request*/, ::bitcoin::BroadcastTransactionResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_BroadcastBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_BroadcastBlock() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::bitcoin::BroadcastBlockRequest, ::bitcoin::BroadcastBlockResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bitcoin::BroadcastBlockRequest* request, ::bitcoin::BroadcastBlockResponse* response) { return this->BroadcastBlock(context, request, response); }));}
    void SetMessageAllocatorFor_BroadcastBlock(
        ::grpc::MessageAllocator< ::bitcoin::BroadcastBlockRequest, ::bitcoin::BroadcastBlockResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bitcoin::BroadcastBlockRequest, ::bitcoin::BroadcastBlockResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_BroadcastBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastBlock(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastBlockRequest* /*request*/, ::bitcoin::BroadcastBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BroadcastBlock(
      ::grpc::CallbackServerContext* /*context*/, const ::bitcoin::BroadcastBlockRequest* /*request*/, ::bitcoin::BroadcastBlockResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetBlockchain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetBlockchain() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::bitcoin::GetBlockchainRequest, ::bitcoin::GetBlockchainResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bitcoin::GetBlockchainRequest* request, ::bitcoin::GetBlockchainResponse* response) { return this->GetBlockchain(context, request, response); }));}
    void SetMessageAllocatorFor_GetBlockchain(
        ::grpc::MessageAllocator< ::bitcoin::GetBlockchainRequest, ::bitcoin::GetBlockchainResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bitcoin::GetBlockchainRequest, ::bitcoin::GetBlockchainResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetBlockchain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockchain(::grpc::ServerContext* /*context*/, const ::bitcoin::GetBlockchainRequest* /*request*/, ::bitcoin::GetBlockchainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBlockchain(
      ::grpc::CallbackServerContext* /*context*/, const ::bitcoin::GetBlockchainRequest* /*request*/, ::bitcoin::GetBlockchainResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetTransactionStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetTransactionStatus() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::bitcoin::GetTransactionStatusRequest, ::bitcoin::GetTransactionStatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bitcoin::GetTransactionStatusRequest* request, ::bitcoin::GetTransactionStatusResponse* response) { return this->GetTransactionStatus(context, request, response); }));}
    void SetMessageAllocatorFor_GetTransactionStatus(
        ::grpc::MessageAllocator< ::bitcoin::GetTransactionStatusRequest, ::bitcoin::GetTransactionStatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bitcoin::GetTransactionStatusRequest, ::bitcoin::GetTransactionStatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetTransactionStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransactionStatus(::grpc::ServerContext* /*context*/, const ::bitcoin::GetTransactionStatusRequest* /*request*/, ::bitcoin::GetTransactionStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTransactionStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::bitcoin::GetTransactionStatusRequest* /*request*/, ::bitcoin::GetTransactionStatusResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_BroadcastTransaction<WithCallbackMethod_BroadcastBlock<WithCallbackMethod_GetBlockchain<WithCallbackMethod_GetTransactionStatus<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastTransactionRequest* /*request*/, ::bitcoin::BroadcastTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_BroadcastBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_BroadcastBlock() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_BroadcastBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastBlock(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastBlockRequest* /*request*/, ::bitcoin::BroadcastBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetBlockchain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetBlockchain() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetBlockchain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockchain(::grpc::ServerContext* /*context*/, const ::bitcoin::GetBlockchainRequest* /*request*/, ::bitcoin::GetBlockchainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetTransactionStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetTransactionStatus() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetTransactionStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransactionStatus(::grpc::ServerContext* /*context*/, const ::bitcoin::GetTransactionStatusRequest* /*request*/, ::bitcoin::GetTransactionStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastTransactionRequest* /*request*/, ::bitcoin::BroadcastTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBroadcastTransaction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_BroadcastBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_BroadcastBlock() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_BroadcastBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastBlock(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastBlockRequest* /*request*/, ::bitcoin::BroadcastBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBroadcastBlock(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetBlockchain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetBlockchain() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetBlockchain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockchain(::grpc::ServerContext* /*context*/, const ::bitcoin::GetBlockchainRequest* /*request*/, ::bitcoin::GetBlockchainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBlockchain(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetTransactionStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetTransactionStatus() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetTransactionStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransactionStatus(::grpc::ServerContext* /*context*/, const ::bitcoin::GetTransactionStatusRequest* /*request*/, ::bitcoin::GetTransactionStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetTransactionStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->BroadcastTransaction(context, request, response); }));
    }
    ~WithRawCallbackMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastTransactionRequest* /*request*/, ::bitcoin::BroadcastTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BroadcastTransaction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_BroadcastBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_BroadcastBlock() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->BroadcastBlock(context, request, response); }));
    }
    ~WithRawCallbackMethod_BroadcastBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BroadcastBlock(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastBlockRequest* /*request*/, ::bitcoin::BroadcastBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* BroadcastBlock(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetBlockchain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetBlockchain() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetBlockchain(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetBlockchain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBlockchain(::grpc::ServerContext* /*context*/, const ::bitcoin::GetBlockchainRequest* /*request*/, ::bitcoin::GetBlockchainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBlockchain(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetTransactionStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetTransactionStatus() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetTransactionStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetTransactionStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetTransactionStatus(::grpc::ServerContext* /*context*/, const ::bitcoin::GetTransactionStatusRequest* /*request*/, ::bitcoin::GetTransactionStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetTransactionStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BroadcastTransaction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_BroadcastTransaction() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bitcoin::BroadcastTransactionRequest, ::bitcoin::BroadcastTransactionResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bitcoin::BroadcastTransactionRequest, ::bitcoin::BroadcastTransactionResponse>* streamer) {
                       return this->StreamedBroadcastTransaction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_BroadcastTransaction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BroadcastTransaction(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastTransactionRequest* /*request*/, ::bitcoin::BroadcastTransactionResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBroadcastTransaction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bitcoin::BroadcastTransactionRequest,::bitcoin::BroadcastTransactionResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_BroadcastBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_BroadcastBlock() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bitcoin::BroadcastBlockRequest, ::bitcoin::BroadcastBlockResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bitcoin::BroadcastBlockRequest, ::bitcoin::BroadcastBlockResponse>* streamer) {
                       return this->StreamedBroadcastBlock(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_BroadcastBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status BroadcastBlock(::grpc::ServerContext* /*context*/, const ::bitcoin::BroadcastBlockRequest* /*request*/, ::bitcoin::BroadcastBlockResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedBroadcastBlock(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bitcoin::BroadcastBlockRequest,::bitcoin::BroadcastBlockResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetBlockchain : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetBlockchain() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bitcoin::GetBlockchainRequest, ::bitcoin::GetBlockchainResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bitcoin::GetBlockchainRequest, ::bitcoin::GetBlockchainResponse>* streamer) {
                       return this->StreamedGetBlockchain(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetBlockchain() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetBlockchain(::grpc::ServerContext* /*context*/, const ::bitcoin::GetBlockchainRequest* /*request*/, ::bitcoin::GetBlockchainResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetBlockchain(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bitcoin::GetBlockchainRequest,::bitcoin::GetBlockchainResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetTransactionStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetTransactionStatus() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bitcoin::GetTransactionStatusRequest, ::bitcoin::GetTransactionStatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bitcoin::GetTransactionStatusRequest, ::bitcoin::GetTransactionStatusResponse>* streamer) {
                       return this->StreamedGetTransactionStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetTransactionStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetTransactionStatus(::grpc::ServerContext* /*context*/, const ::bitcoin::GetTransactionStatusRequest* /*request*/, ::bitcoin::GetTransactionStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetTransactionStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bitcoin::GetTransactionStatusRequest,::bitcoin::GetTransactionStatusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_BroadcastTransaction<WithStreamedUnaryMethod_BroadcastBlock<WithStreamedUnaryMethod_GetBlockchain<WithStreamedUnaryMethod_GetTransactionStatus<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_BroadcastTransaction<WithStreamedUnaryMethod_BroadcastBlock<WithStreamedUnaryMethod_GetBlockchain<WithStreamedUnaryMethod_GetTransactionStatus<Service > > > > StreamedService;
};

}  // namespace bitcoin


#endif  // GRPC_node_5fservice_2eproto__INCLUDED
