// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: node_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_node_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_node_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "transaction.pb.h"
#include "block.pb.h"
#include "node.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_node_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_node_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_node_5fservice_2eproto;
namespace bitcoin {
class BroadcastBlockRequest;
struct BroadcastBlockRequestDefaultTypeInternal;
extern BroadcastBlockRequestDefaultTypeInternal _BroadcastBlockRequest_default_instance_;
class BroadcastBlockResponse;
struct BroadcastBlockResponseDefaultTypeInternal;
extern BroadcastBlockResponseDefaultTypeInternal _BroadcastBlockResponse_default_instance_;
class BroadcastTransactionRequest;
struct BroadcastTransactionRequestDefaultTypeInternal;
extern BroadcastTransactionRequestDefaultTypeInternal _BroadcastTransactionRequest_default_instance_;
class BroadcastTransactionResponse;
struct BroadcastTransactionResponseDefaultTypeInternal;
extern BroadcastTransactionResponseDefaultTypeInternal _BroadcastTransactionResponse_default_instance_;
class GetBlockchainRequest;
struct GetBlockchainRequestDefaultTypeInternal;
extern GetBlockchainRequestDefaultTypeInternal _GetBlockchainRequest_default_instance_;
class GetBlockchainResponse;
struct GetBlockchainResponseDefaultTypeInternal;
extern GetBlockchainResponseDefaultTypeInternal _GetBlockchainResponse_default_instance_;
class GetTransactionStatusRequest;
struct GetTransactionStatusRequestDefaultTypeInternal;
extern GetTransactionStatusRequestDefaultTypeInternal _GetTransactionStatusRequest_default_instance_;
class GetTransactionStatusResponse;
struct GetTransactionStatusResponseDefaultTypeInternal;
extern GetTransactionStatusResponseDefaultTypeInternal _GetTransactionStatusResponse_default_instance_;
}  // namespace bitcoin
PROTOBUF_NAMESPACE_OPEN
template<> ::bitcoin::BroadcastBlockRequest* Arena::CreateMaybeMessage<::bitcoin::BroadcastBlockRequest>(Arena*);
template<> ::bitcoin::BroadcastBlockResponse* Arena::CreateMaybeMessage<::bitcoin::BroadcastBlockResponse>(Arena*);
template<> ::bitcoin::BroadcastTransactionRequest* Arena::CreateMaybeMessage<::bitcoin::BroadcastTransactionRequest>(Arena*);
template<> ::bitcoin::BroadcastTransactionResponse* Arena::CreateMaybeMessage<::bitcoin::BroadcastTransactionResponse>(Arena*);
template<> ::bitcoin::GetBlockchainRequest* Arena::CreateMaybeMessage<::bitcoin::GetBlockchainRequest>(Arena*);
template<> ::bitcoin::GetBlockchainResponse* Arena::CreateMaybeMessage<::bitcoin::GetBlockchainResponse>(Arena*);
template<> ::bitcoin::GetTransactionStatusRequest* Arena::CreateMaybeMessage<::bitcoin::GetTransactionStatusRequest>(Arena*);
template<> ::bitcoin::GetTransactionStatusResponse* Arena::CreateMaybeMessage<::bitcoin::GetTransactionStatusResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bitcoin {

// ===================================================================

class BroadcastTransactionRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.BroadcastTransactionRequest) */ {
 public:
  inline BroadcastTransactionRequest() : BroadcastTransactionRequest(nullptr) {}
  ~BroadcastTransactionRequest() override;
  explicit PROTOBUF_CONSTEXPR BroadcastTransactionRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BroadcastTransactionRequest(const BroadcastTransactionRequest& from);
  BroadcastTransactionRequest(BroadcastTransactionRequest&& from) noexcept
    : BroadcastTransactionRequest() {
    *this = ::std::move(from);
  }

  inline BroadcastTransactionRequest& operator=(const BroadcastTransactionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BroadcastTransactionRequest& operator=(BroadcastTransactionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BroadcastTransactionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BroadcastTransactionRequest* internal_default_instance() {
    return reinterpret_cast<const BroadcastTransactionRequest*>(
               &_BroadcastTransactionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BroadcastTransactionRequest& a, BroadcastTransactionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BroadcastTransactionRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BroadcastTransactionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BroadcastTransactionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BroadcastTransactionRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BroadcastTransactionRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BroadcastTransactionRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BroadcastTransactionRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.BroadcastTransactionRequest";
  }
  protected:
  explicit BroadcastTransactionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransactionFieldNumber = 1,
  };
  // .bitcoin.Transaction transaction = 1;
  bool has_transaction() const;
  private:
  bool _internal_has_transaction() const;
  public:
  void clear_transaction();
  const ::bitcoin::Transaction& transaction() const;
  PROTOBUF_NODISCARD ::bitcoin::Transaction* release_transaction();
  ::bitcoin::Transaction* mutable_transaction();
  void set_allocated_transaction(::bitcoin::Transaction* transaction);
  private:
  const ::bitcoin::Transaction& _internal_transaction() const;
  ::bitcoin::Transaction* _internal_mutable_transaction();
  public:
  void unsafe_arena_set_allocated_transaction(
      ::bitcoin::Transaction* transaction);
  ::bitcoin::Transaction* unsafe_arena_release_transaction();

  // @@protoc_insertion_point(class_scope:bitcoin.BroadcastTransactionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::bitcoin::Transaction* transaction_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_node_5fservice_2eproto;
};
// -------------------------------------------------------------------

class BroadcastTransactionResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.BroadcastTransactionResponse) */ {
 public:
  inline BroadcastTransactionResponse() : BroadcastTransactionResponse(nullptr) {}
  ~BroadcastTransactionResponse() override;
  explicit PROTOBUF_CONSTEXPR BroadcastTransactionResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BroadcastTransactionResponse(const BroadcastTransactionResponse& from);
  BroadcastTransactionResponse(BroadcastTransactionResponse&& from) noexcept
    : BroadcastTransactionResponse() {
    *this = ::std::move(from);
  }

  inline BroadcastTransactionResponse& operator=(const BroadcastTransactionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BroadcastTransactionResponse& operator=(BroadcastTransactionResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BroadcastTransactionResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BroadcastTransactionResponse* internal_default_instance() {
    return reinterpret_cast<const BroadcastTransactionResponse*>(
               &_BroadcastTransactionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BroadcastTransactionResponse& a, BroadcastTransactionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BroadcastTransactionResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BroadcastTransactionResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BroadcastTransactionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BroadcastTransactionResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BroadcastTransactionResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BroadcastTransactionResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BroadcastTransactionResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.BroadcastTransactionResponse";
  }
  protected:
  explicit BroadcastTransactionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kNodeIdFieldNumber = 3,
    kAcceptedFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // string node_id = 3;
  void clear_node_id();
  const std::string& node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // bool accepted = 1;
  void clear_accepted();
  bool accepted() const;
  void set_accepted(bool value);
  private:
  bool _internal_accepted() const;
  void _internal_set_accepted(bool value);
  public:

  // @@protoc_insertion_point(class_scope:bitcoin.BroadcastTransactionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
  bool accepted_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_node_5fservice_2eproto;
};
// -------------------------------------------------------------------

class BroadcastBlockRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.BroadcastBlockRequest) */ {
 public:
  inline BroadcastBlockRequest() : BroadcastBlockRequest(nullptr) {}
  ~BroadcastBlockRequest() override;
  explicit PROTOBUF_CONSTEXPR BroadcastBlockRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BroadcastBlockRequest(const BroadcastBlockRequest& from);
  BroadcastBlockRequest(BroadcastBlockRequest&& from) noexcept
    : BroadcastBlockRequest() {
    *this = ::std::move(from);
  }

  inline BroadcastBlockRequest& operator=(const BroadcastBlockRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BroadcastBlockRequest& operator=(BroadcastBlockRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BroadcastBlockRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const BroadcastBlockRequest* internal_default_instance() {
    return reinterpret_cast<const BroadcastBlockRequest*>(
               &_BroadcastBlockRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(BroadcastBlockRequest& a, BroadcastBlockRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(BroadcastBlockRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BroadcastBlockRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BroadcastBlockRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BroadcastBlockRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BroadcastBlockRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BroadcastBlockRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BroadcastBlockRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.BroadcastBlockRequest";
  }
  protected:
  explicit BroadcastBlockRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlockFieldNumber = 1,
  };
  // .bitcoin.Block block = 1;
  bool has_block() const;
  private:
  bool _internal_has_block() const;
  public:
  void clear_block();
  const ::bitcoin::Block& block() const;
  PROTOBUF_NODISCARD ::bitcoin::Block* release_block();
  ::bitcoin::Block* mutable_block();
  void set_allocated_block(::bitcoin::Block* block);
  private:
  const ::bitcoin::Block& _internal_block() const;
  ::bitcoin::Block* _internal_mutable_block();
  public:
  void unsafe_arena_set_allocated_block(
      ::bitcoin::Block* block);
  ::bitcoin::Block* unsafe_arena_release_block();

  // @@protoc_insertion_point(class_scope:bitcoin.BroadcastBlockRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::bitcoin::Block* block_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_node_5fservice_2eproto;
};
// -------------------------------------------------------------------

class BroadcastBlockResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.BroadcastBlockResponse) */ {
 public:
  inline BroadcastBlockResponse() : BroadcastBlockResponse(nullptr) {}
  ~BroadcastBlockResponse() override;
  explicit PROTOBUF_CONSTEXPR BroadcastBlockResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BroadcastBlockResponse(const BroadcastBlockResponse& from);
  BroadcastBlockResponse(BroadcastBlockResponse&& from) noexcept
    : BroadcastBlockResponse() {
    *this = ::std::move(from);
  }

  inline BroadcastBlockResponse& operator=(const BroadcastBlockResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BroadcastBlockResponse& operator=(BroadcastBlockResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BroadcastBlockResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BroadcastBlockResponse* internal_default_instance() {
    return reinterpret_cast<const BroadcastBlockResponse*>(
               &_BroadcastBlockResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(BroadcastBlockResponse& a, BroadcastBlockResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BroadcastBlockResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BroadcastBlockResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BroadcastBlockResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BroadcastBlockResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BroadcastBlockResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const BroadcastBlockResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BroadcastBlockResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.BroadcastBlockResponse";
  }
  protected:
  explicit BroadcastBlockResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kNodeIdFieldNumber = 3,
    kAcceptedFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // string node_id = 3;
  void clear_node_id();
  const std::string& node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // bool accepted = 1;
  void clear_accepted();
  bool accepted() const;
  void set_accepted(bool value);
  private:
  bool _internal_accepted() const;
  void _internal_set_accepted(bool value);
  public:

  // @@protoc_insertion_point(class_scope:bitcoin.BroadcastBlockResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
  bool accepted_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_node_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetBlockchainRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.GetBlockchainRequest) */ {
 public:
  inline GetBlockchainRequest() : GetBlockchainRequest(nullptr) {}
  ~GetBlockchainRequest() override;
  explicit PROTOBUF_CONSTEXPR GetBlockchainRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetBlockchainRequest(const GetBlockchainRequest& from);
  GetBlockchainRequest(GetBlockchainRequest&& from) noexcept
    : GetBlockchainRequest() {
    *this = ::std::move(from);
  }

  inline GetBlockchainRequest& operator=(const GetBlockchainRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetBlockchainRequest& operator=(GetBlockchainRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetBlockchainRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetBlockchainRequest* internal_default_instance() {
    return reinterpret_cast<const GetBlockchainRequest*>(
               &_GetBlockchainRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(GetBlockchainRequest& a, GetBlockchainRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetBlockchainRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetBlockchainRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetBlockchainRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetBlockchainRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetBlockchainRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetBlockchainRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetBlockchainRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.GetBlockchainRequest";
  }
  protected:
  explicit GetBlockchainRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStartIndexFieldNumber = 1,
  };
  // uint64 start_index = 1;
  void clear_start_index();
  uint64_t start_index() const;
  void set_start_index(uint64_t value);
  private:
  uint64_t _internal_start_index() const;
  void _internal_set_start_index(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:bitcoin.GetBlockchainRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t start_index_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_node_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetBlockchainResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.GetBlockchainResponse) */ {
 public:
  inline GetBlockchainResponse() : GetBlockchainResponse(nullptr) {}
  ~GetBlockchainResponse() override;
  explicit PROTOBUF_CONSTEXPR GetBlockchainResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetBlockchainResponse(const GetBlockchainResponse& from);
  GetBlockchainResponse(GetBlockchainResponse&& from) noexcept
    : GetBlockchainResponse() {
    *this = ::std::move(from);
  }

  inline GetBlockchainResponse& operator=(const GetBlockchainResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetBlockchainResponse& operator=(GetBlockchainResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetBlockchainResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetBlockchainResponse* internal_default_instance() {
    return reinterpret_cast<const GetBlockchainResponse*>(
               &_GetBlockchainResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(GetBlockchainResponse& a, GetBlockchainResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetBlockchainResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetBlockchainResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetBlockchainResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetBlockchainResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetBlockchainResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetBlockchainResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetBlockchainResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.GetBlockchainResponse";
  }
  protected:
  explicit GetBlockchainResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlocksFieldNumber = 1,
  };
  // repeated .bitcoin.Block blocks = 1;
  int blocks_size() const;
  private:
  int _internal_blocks_size() const;
  public:
  void clear_blocks();
  ::bitcoin::Block* mutable_blocks(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Block >*
      mutable_blocks();
  private:
  const ::bitcoin::Block& _internal_blocks(int index) const;
  ::bitcoin::Block* _internal_add_blocks();
  public:
  const ::bitcoin::Block& blocks(int index) const;
  ::bitcoin::Block* add_blocks();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Block >&
      blocks() const;

  // @@protoc_insertion_point(class_scope:bitcoin.GetBlockchainResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Block > blocks_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_node_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetTransactionStatusRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.GetTransactionStatusRequest) */ {
 public:
  inline GetTransactionStatusRequest() : GetTransactionStatusRequest(nullptr) {}
  ~GetTransactionStatusRequest() override;
  explicit PROTOBUF_CONSTEXPR GetTransactionStatusRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetTransactionStatusRequest(const GetTransactionStatusRequest& from);
  GetTransactionStatusRequest(GetTransactionStatusRequest&& from) noexcept
    : GetTransactionStatusRequest() {
    *this = ::std::move(from);
  }

  inline GetTransactionStatusRequest& operator=(const GetTransactionStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetTransactionStatusRequest& operator=(GetTransactionStatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetTransactionStatusRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetTransactionStatusRequest* internal_default_instance() {
    return reinterpret_cast<const GetTransactionStatusRequest*>(
               &_GetTransactionStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(GetTransactionStatusRequest& a, GetTransactionStatusRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetTransactionStatusRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetTransactionStatusRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetTransactionStatusRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetTransactionStatusRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetTransactionStatusRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetTransactionStatusRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetTransactionStatusRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.GetTransactionStatusRequest";
  }
  protected:
  explicit GetTransactionStatusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransactionIdFieldNumber = 1,
  };
  // bytes transaction_id = 1;
  void clear_transaction_id();
  const std::string& transaction_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_transaction_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_transaction_id();
  PROTOBUF_NODISCARD std::string* release_transaction_id();
  void set_allocated_transaction_id(std::string* transaction_id);
  private:
  const std::string& _internal_transaction_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_transaction_id(const std::string& value);
  std::string* _internal_mutable_transaction_id();
  public:

  // @@protoc_insertion_point(class_scope:bitcoin.GetTransactionStatusRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr transaction_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_node_5fservice_2eproto;
};
// -------------------------------------------------------------------

class GetTransactionStatusResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.GetTransactionStatusResponse) */ {
 public:
  inline GetTransactionStatusResponse() : GetTransactionStatusResponse(nullptr) {}
  ~GetTransactionStatusResponse() override;
  explicit PROTOBUF_CONSTEXPR GetTransactionStatusResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetTransactionStatusResponse(const GetTransactionStatusResponse& from);
  GetTransactionStatusResponse(GetTransactionStatusResponse&& from) noexcept
    : GetTransactionStatusResponse() {
    *this = ::std::move(from);
  }

  inline GetTransactionStatusResponse& operator=(const GetTransactionStatusResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetTransactionStatusResponse& operator=(GetTransactionStatusResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetTransactionStatusResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetTransactionStatusResponse* internal_default_instance() {
    return reinterpret_cast<const GetTransactionStatusResponse*>(
               &_GetTransactionStatusResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(GetTransactionStatusResponse& a, GetTransactionStatusResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetTransactionStatusResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetTransactionStatusResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetTransactionStatusResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetTransactionStatusResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetTransactionStatusResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetTransactionStatusResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetTransactionStatusResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.GetTransactionStatusResponse";
  }
  protected:
  explicit GetTransactionStatusResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlockHashFieldNumber = 2,
    kNodeIdFieldNumber = 3,
    kConfirmedFieldNumber = 1,
  };
  // bytes block_hash = 2;
  void clear_block_hash();
  const std::string& block_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_block_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_block_hash();
  PROTOBUF_NODISCARD std::string* release_block_hash();
  void set_allocated_block_hash(std::string* block_hash);
  private:
  const std::string& _internal_block_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_block_hash(const std::string& value);
  std::string* _internal_mutable_block_hash();
  public:

  // string node_id = 3;
  void clear_node_id();
  const std::string& node_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_node_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_node_id();
  PROTOBUF_NODISCARD std::string* release_node_id();
  void set_allocated_node_id(std::string* node_id);
  private:
  const std::string& _internal_node_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_node_id(const std::string& value);
  std::string* _internal_mutable_node_id();
  public:

  // bool confirmed = 1;
  void clear_confirmed();
  bool confirmed() const;
  void set_confirmed(bool value);
  private:
  bool _internal_confirmed() const;
  void _internal_set_confirmed(bool value);
  public:

  // @@protoc_insertion_point(class_scope:bitcoin.GetTransactionStatusResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr block_hash_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr node_id_;
  bool confirmed_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_node_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BroadcastTransactionRequest

// .bitcoin.Transaction transaction = 1;
inline bool BroadcastTransactionRequest::_internal_has_transaction() const {
  return this != internal_default_instance() && transaction_ != nullptr;
}
inline bool BroadcastTransactionRequest::has_transaction() const {
  return _internal_has_transaction();
}
inline const ::bitcoin::Transaction& BroadcastTransactionRequest::_internal_transaction() const {
  const ::bitcoin::Transaction* p = transaction_;
  return p != nullptr ? *p : reinterpret_cast<const ::bitcoin::Transaction&>(
      ::bitcoin::_Transaction_default_instance_);
}
inline const ::bitcoin::Transaction& BroadcastTransactionRequest::transaction() const {
  // @@protoc_insertion_point(field_get:bitcoin.BroadcastTransactionRequest.transaction)
  return _internal_transaction();
}
inline void BroadcastTransactionRequest::unsafe_arena_set_allocated_transaction(
    ::bitcoin::Transaction* transaction) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(transaction_);
  }
  transaction_ = transaction;
  if (transaction) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bitcoin.BroadcastTransactionRequest.transaction)
}
inline ::bitcoin::Transaction* BroadcastTransactionRequest::release_transaction() {
  
  ::bitcoin::Transaction* temp = transaction_;
  transaction_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::bitcoin::Transaction* BroadcastTransactionRequest::unsafe_arena_release_transaction() {
  // @@protoc_insertion_point(field_release:bitcoin.BroadcastTransactionRequest.transaction)
  
  ::bitcoin::Transaction* temp = transaction_;
  transaction_ = nullptr;
  return temp;
}
inline ::bitcoin::Transaction* BroadcastTransactionRequest::_internal_mutable_transaction() {
  
  if (transaction_ == nullptr) {
    auto* p = CreateMaybeMessage<::bitcoin::Transaction>(GetArenaForAllocation());
    transaction_ = p;
  }
  return transaction_;
}
inline ::bitcoin::Transaction* BroadcastTransactionRequest::mutable_transaction() {
  ::bitcoin::Transaction* _msg = _internal_mutable_transaction();
  // @@protoc_insertion_point(field_mutable:bitcoin.BroadcastTransactionRequest.transaction)
  return _msg;
}
inline void BroadcastTransactionRequest::set_allocated_transaction(::bitcoin::Transaction* transaction) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(transaction_);
  }
  if (transaction) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(transaction));
    if (message_arena != submessage_arena) {
      transaction = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, transaction, submessage_arena);
    }
    
  } else {
    
  }
  transaction_ = transaction;
  // @@protoc_insertion_point(field_set_allocated:bitcoin.BroadcastTransactionRequest.transaction)
}

// -------------------------------------------------------------------

// BroadcastTransactionResponse

// bool accepted = 1;
inline void BroadcastTransactionResponse::clear_accepted() {
  accepted_ = false;
}
inline bool BroadcastTransactionResponse::_internal_accepted() const {
  return accepted_;
}
inline bool BroadcastTransactionResponse::accepted() const {
  // @@protoc_insertion_point(field_get:bitcoin.BroadcastTransactionResponse.accepted)
  return _internal_accepted();
}
inline void BroadcastTransactionResponse::_internal_set_accepted(bool value) {
  
  accepted_ = value;
}
inline void BroadcastTransactionResponse::set_accepted(bool value) {
  _internal_set_accepted(value);
  // @@protoc_insertion_point(field_set:bitcoin.BroadcastTransactionResponse.accepted)
}

// string message = 2;
inline void BroadcastTransactionResponse::clear_message() {
  message_.ClearToEmpty();
}
inline const std::string& BroadcastTransactionResponse::message() const {
  // @@protoc_insertion_point(field_get:bitcoin.BroadcastTransactionResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BroadcastTransactionResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.BroadcastTransactionResponse.message)
}
inline std::string* BroadcastTransactionResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:bitcoin.BroadcastTransactionResponse.message)
  return _s;
}
inline const std::string& BroadcastTransactionResponse::_internal_message() const {
  return message_.Get();
}
inline void BroadcastTransactionResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(value, GetArenaForAllocation());
}
inline std::string* BroadcastTransactionResponse::_internal_mutable_message() {
  
  return message_.Mutable(GetArenaForAllocation());
}
inline std::string* BroadcastTransactionResponse::release_message() {
  // @@protoc_insertion_point(field_release:bitcoin.BroadcastTransactionResponse.message)
  return message_.Release();
}
inline void BroadcastTransactionResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (message_.IsDefault()) {
    message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.BroadcastTransactionResponse.message)
}

// string node_id = 3;
inline void BroadcastTransactionResponse::clear_node_id() {
  node_id_.ClearToEmpty();
}
inline const std::string& BroadcastTransactionResponse::node_id() const {
  // @@protoc_insertion_point(field_get:bitcoin.BroadcastTransactionResponse.node_id)
  return _internal_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BroadcastTransactionResponse::set_node_id(ArgT0&& arg0, ArgT... args) {
 
 node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.BroadcastTransactionResponse.node_id)
}
inline std::string* BroadcastTransactionResponse::mutable_node_id() {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:bitcoin.BroadcastTransactionResponse.node_id)
  return _s;
}
inline const std::string& BroadcastTransactionResponse::_internal_node_id() const {
  return node_id_.Get();
}
inline void BroadcastTransactionResponse::_internal_set_node_id(const std::string& value) {
  
  node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* BroadcastTransactionResponse::_internal_mutable_node_id() {
  
  return node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* BroadcastTransactionResponse::release_node_id() {
  // @@protoc_insertion_point(field_release:bitcoin.BroadcastTransactionResponse.node_id)
  return node_id_.Release();
}
inline void BroadcastTransactionResponse::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    
  } else {
    
  }
  node_id_.SetAllocated(node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (node_id_.IsDefault()) {
    node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.BroadcastTransactionResponse.node_id)
}

// -------------------------------------------------------------------

// BroadcastBlockRequest

// .bitcoin.Block block = 1;
inline bool BroadcastBlockRequest::_internal_has_block() const {
  return this != internal_default_instance() && block_ != nullptr;
}
inline bool BroadcastBlockRequest::has_block() const {
  return _internal_has_block();
}
inline const ::bitcoin::Block& BroadcastBlockRequest::_internal_block() const {
  const ::bitcoin::Block* p = block_;
  return p != nullptr ? *p : reinterpret_cast<const ::bitcoin::Block&>(
      ::bitcoin::_Block_default_instance_);
}
inline const ::bitcoin::Block& BroadcastBlockRequest::block() const {
  // @@protoc_insertion_point(field_get:bitcoin.BroadcastBlockRequest.block)
  return _internal_block();
}
inline void BroadcastBlockRequest::unsafe_arena_set_allocated_block(
    ::bitcoin::Block* block) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(block_);
  }
  block_ = block;
  if (block) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:bitcoin.BroadcastBlockRequest.block)
}
inline ::bitcoin::Block* BroadcastBlockRequest::release_block() {
  
  ::bitcoin::Block* temp = block_;
  block_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::bitcoin::Block* BroadcastBlockRequest::unsafe_arena_release_block() {
  // @@protoc_insertion_point(field_release:bitcoin.BroadcastBlockRequest.block)
  
  ::bitcoin::Block* temp = block_;
  block_ = nullptr;
  return temp;
}
inline ::bitcoin::Block* BroadcastBlockRequest::_internal_mutable_block() {
  
  if (block_ == nullptr) {
    auto* p = CreateMaybeMessage<::bitcoin::Block>(GetArenaForAllocation());
    block_ = p;
  }
  return block_;
}
inline ::bitcoin::Block* BroadcastBlockRequest::mutable_block() {
  ::bitcoin::Block* _msg = _internal_mutable_block();
  // @@protoc_insertion_point(field_mutable:bitcoin.BroadcastBlockRequest.block)
  return _msg;
}
inline void BroadcastBlockRequest::set_allocated_block(::bitcoin::Block* block) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(block_);
  }
  if (block) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(block));
    if (message_arena != submessage_arena) {
      block = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, block, submessage_arena);
    }
    
  } else {
    
  }
  block_ = block;
  // @@protoc_insertion_point(field_set_allocated:bitcoin.BroadcastBlockRequest.block)
}

// -------------------------------------------------------------------

// BroadcastBlockResponse

// bool accepted = 1;
inline void BroadcastBlockResponse::clear_accepted() {
  accepted_ = false;
}
inline bool BroadcastBlockResponse::_internal_accepted() const {
  return accepted_;
}
inline bool BroadcastBlockResponse::accepted() const {
  // @@protoc_insertion_point(field_get:bitcoin.BroadcastBlockResponse.accepted)
  return _internal_accepted();
}
inline void BroadcastBlockResponse::_internal_set_accepted(bool value) {
  
  accepted_ = value;
}
inline void BroadcastBlockResponse::set_accepted(bool value) {
  _internal_set_accepted(value);
  // @@protoc_insertion_point(field_set:bitcoin.BroadcastBlockResponse.accepted)
}

// string message = 2;
inline void BroadcastBlockResponse::clear_message() {
  message_.ClearToEmpty();
}
inline const std::string& BroadcastBlockResponse::message() const {
  // @@protoc_insertion_point(field_get:bitcoin.BroadcastBlockResponse.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BroadcastBlockResponse::set_message(ArgT0&& arg0, ArgT... args) {
 
 message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.BroadcastBlockResponse.message)
}
inline std::string* BroadcastBlockResponse::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:bitcoin.BroadcastBlockResponse.message)
  return _s;
}
inline const std::string& BroadcastBlockResponse::_internal_message() const {
  return message_.Get();
}
inline void BroadcastBlockResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(value, GetArenaForAllocation());
}
inline std::string* BroadcastBlockResponse::_internal_mutable_message() {
  
  return message_.Mutable(GetArenaForAllocation());
}
inline std::string* BroadcastBlockResponse::release_message() {
  // @@protoc_insertion_point(field_release:bitcoin.BroadcastBlockResponse.message)
  return message_.Release();
}
inline void BroadcastBlockResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (message_.IsDefault()) {
    message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.BroadcastBlockResponse.message)
}

// string node_id = 3;
inline void BroadcastBlockResponse::clear_node_id() {
  node_id_.ClearToEmpty();
}
inline const std::string& BroadcastBlockResponse::node_id() const {
  // @@protoc_insertion_point(field_get:bitcoin.BroadcastBlockResponse.node_id)
  return _internal_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BroadcastBlockResponse::set_node_id(ArgT0&& arg0, ArgT... args) {
 
 node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.BroadcastBlockResponse.node_id)
}
inline std::string* BroadcastBlockResponse::mutable_node_id() {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:bitcoin.BroadcastBlockResponse.node_id)
  return _s;
}
inline const std::string& BroadcastBlockResponse::_internal_node_id() const {
  return node_id_.Get();
}
inline void BroadcastBlockResponse::_internal_set_node_id(const std::string& value) {
  
  node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* BroadcastBlockResponse::_internal_mutable_node_id() {
  
  return node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* BroadcastBlockResponse::release_node_id() {
  // @@protoc_insertion_point(field_release:bitcoin.BroadcastBlockResponse.node_id)
  return node_id_.Release();
}
inline void BroadcastBlockResponse::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    
  } else {
    
  }
  node_id_.SetAllocated(node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (node_id_.IsDefault()) {
    node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.BroadcastBlockResponse.node_id)
}

// -------------------------------------------------------------------

// GetBlockchainRequest

// uint64 start_index = 1;
inline void GetBlockchainRequest::clear_start_index() {
  start_index_ = uint64_t{0u};
}
inline uint64_t GetBlockchainRequest::_internal_start_index() const {
  return start_index_;
}
inline uint64_t GetBlockchainRequest::start_index() const {
  // @@protoc_insertion_point(field_get:bitcoin.GetBlockchainRequest.start_index)
  return _internal_start_index();
}
inline void GetBlockchainRequest::_internal_set_start_index(uint64_t value) {
  
  start_index_ = value;
}
inline void GetBlockchainRequest::set_start_index(uint64_t value) {
  _internal_set_start_index(value);
  // @@protoc_insertion_point(field_set:bitcoin.GetBlockchainRequest.start_index)
}

// -------------------------------------------------------------------

// GetBlockchainResponse

// repeated .bitcoin.Block blocks = 1;
inline int GetBlockchainResponse::_internal_blocks_size() const {
  return blocks_.size();
}
inline int GetBlockchainResponse::blocks_size() const {
  return _internal_blocks_size();
}
inline ::bitcoin::Block* GetBlockchainResponse::mutable_blocks(int index) {
  // @@protoc_insertion_point(field_mutable:bitcoin.GetBlockchainResponse.blocks)
  return blocks_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Block >*
GetBlockchainResponse::mutable_blocks() {
  // @@protoc_insertion_point(field_mutable_list:bitcoin.GetBlockchainResponse.blocks)
  return &blocks_;
}
inline const ::bitcoin::Block& GetBlockchainResponse::_internal_blocks(int index) const {
  return blocks_.Get(index);
}
inline const ::bitcoin::Block& GetBlockchainResponse::blocks(int index) const {
  // @@protoc_insertion_point(field_get:bitcoin.GetBlockchainResponse.blocks)
  return _internal_blocks(index);
}
inline ::bitcoin::Block* GetBlockchainResponse::_internal_add_blocks() {
  return blocks_.Add();
}
inline ::bitcoin::Block* GetBlockchainResponse::add_blocks() {
  ::bitcoin::Block* _add = _internal_add_blocks();
  // @@protoc_insertion_point(field_add:bitcoin.GetBlockchainResponse.blocks)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bitcoin::Block >&
GetBlockchainResponse::blocks() const {
  // @@protoc_insertion_point(field_list:bitcoin.GetBlockchainResponse.blocks)
  return blocks_;
}

// -------------------------------------------------------------------

// GetTransactionStatusRequest

// bytes transaction_id = 1;
inline void GetTransactionStatusRequest::clear_transaction_id() {
  transaction_id_.ClearToEmpty();
}
inline const std::string& GetTransactionStatusRequest::transaction_id() const {
  // @@protoc_insertion_point(field_get:bitcoin.GetTransactionStatusRequest.transaction_id)
  return _internal_transaction_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetTransactionStatusRequest::set_transaction_id(ArgT0&& arg0, ArgT... args) {
 
 transaction_id_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.GetTransactionStatusRequest.transaction_id)
}
inline std::string* GetTransactionStatusRequest::mutable_transaction_id() {
  std::string* _s = _internal_mutable_transaction_id();
  // @@protoc_insertion_point(field_mutable:bitcoin.GetTransactionStatusRequest.transaction_id)
  return _s;
}
inline const std::string& GetTransactionStatusRequest::_internal_transaction_id() const {
  return transaction_id_.Get();
}
inline void GetTransactionStatusRequest::_internal_set_transaction_id(const std::string& value) {
  
  transaction_id_.Set(value, GetArenaForAllocation());
}
inline std::string* GetTransactionStatusRequest::_internal_mutable_transaction_id() {
  
  return transaction_id_.Mutable(GetArenaForAllocation());
}
inline std::string* GetTransactionStatusRequest::release_transaction_id() {
  // @@protoc_insertion_point(field_release:bitcoin.GetTransactionStatusRequest.transaction_id)
  return transaction_id_.Release();
}
inline void GetTransactionStatusRequest::set_allocated_transaction_id(std::string* transaction_id) {
  if (transaction_id != nullptr) {
    
  } else {
    
  }
  transaction_id_.SetAllocated(transaction_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (transaction_id_.IsDefault()) {
    transaction_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.GetTransactionStatusRequest.transaction_id)
}

// -------------------------------------------------------------------

// GetTransactionStatusResponse

// bool confirmed = 1;
inline void GetTransactionStatusResponse::clear_confirmed() {
  confirmed_ = false;
}
inline bool GetTransactionStatusResponse::_internal_confirmed() const {
  return confirmed_;
}
inline bool GetTransactionStatusResponse::confirmed() const {
  // @@protoc_insertion_point(field_get:bitcoin.GetTransactionStatusResponse.confirmed)
  return _internal_confirmed();
}
inline void GetTransactionStatusResponse::_internal_set_confirmed(bool value) {
  
  confirmed_ = value;
}
inline void GetTransactionStatusResponse::set_confirmed(bool value) {
  _internal_set_confirmed(value);
  // @@protoc_insertion_point(field_set:bitcoin.GetTransactionStatusResponse.confirmed)
}

// bytes block_hash = 2;
inline void GetTransactionStatusResponse::clear_block_hash() {
  block_hash_.ClearToEmpty();
}
inline const std::string& GetTransactionStatusResponse::block_hash() const {
  // @@protoc_insertion_point(field_get:bitcoin.GetTransactionStatusResponse.block_hash)
  return _internal_block_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetTransactionStatusResponse::set_block_hash(ArgT0&& arg0, ArgT... args) {
 
 block_hash_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.GetTransactionStatusResponse.block_hash)
}
inline std::string* GetTransactionStatusResponse::mutable_block_hash() {
  std::string* _s = _internal_mutable_block_hash();
  // @@protoc_insertion_point(field_mutable:bitcoin.GetTransactionStatusResponse.block_hash)
  return _s;
}
inline const std::string& GetTransactionStatusResponse::_internal_block_hash() const {
  return block_hash_.Get();
}
inline void GetTransactionStatusResponse::_internal_set_block_hash(const std::string& value) {
  
  block_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* GetTransactionStatusResponse::_internal_mutable_block_hash() {
  
  return block_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* GetTransactionStatusResponse::release_block_hash() {
  // @@protoc_insertion_point(field_release:bitcoin.GetTransactionStatusResponse.block_hash)
  return block_hash_.Release();
}
inline void GetTransactionStatusResponse::set_allocated_block_hash(std::string* block_hash) {
  if (block_hash != nullptr) {
    
  } else {
    
  }
  block_hash_.SetAllocated(block_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (block_hash_.IsDefault()) {
    block_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.GetTransactionStatusResponse.block_hash)
}

// string node_id = 3;
inline void GetTransactionStatusResponse::clear_node_id() {
  node_id_.ClearToEmpty();
}
inline const std::string& GetTransactionStatusResponse::node_id() const {
  // @@protoc_insertion_point(field_get:bitcoin.GetTransactionStatusResponse.node_id)
  return _internal_node_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void GetTransactionStatusResponse::set_node_id(ArgT0&& arg0, ArgT... args) {
 
 node_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.GetTransactionStatusResponse.node_id)
}
inline std::string* GetTransactionStatusResponse::mutable_node_id() {
  std::string* _s = _internal_mutable_node_id();
  // @@protoc_insertion_point(field_mutable:bitcoin.GetTransactionStatusResponse.node_id)
  return _s;
}
inline const std::string& GetTransactionStatusResponse::_internal_node_id() const {
  return node_id_.Get();
}
inline void GetTransactionStatusResponse::_internal_set_node_id(const std::string& value) {
  
  node_id_.Set(value, GetArenaForAllocation());
}
inline std::string* GetTransactionStatusResponse::_internal_mutable_node_id() {
  
  return node_id_.Mutable(GetArenaForAllocation());
}
inline std::string* GetTransactionStatusResponse::release_node_id() {
  // @@protoc_insertion_point(field_release:bitcoin.GetTransactionStatusResponse.node_id)
  return node_id_.Release();
}
inline void GetTransactionStatusResponse::set_allocated_node_id(std::string* node_id) {
  if (node_id != nullptr) {
    
  } else {
    
  }
  node_id_.SetAllocated(node_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (node_id_.IsDefault()) {
    node_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.GetTransactionStatusResponse.node_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace bitcoin

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_node_5fservice_2eproto
