// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node_service.proto

#include "node_service.pb.h"
#include "node_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace bitcoin {

static const char* NodeService_method_names[] = {
  "/bitcoin.NodeService/BroadcastTransaction",
  "/bitcoin.NodeService/BroadcastBlock",
  "/bitcoin.NodeService/GetBlockchain",
  "/bitcoin.NodeService/GetTransactionStatus",
};

std::unique_ptr< NodeService::Stub> NodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NodeService::Stub> stub(new NodeService::Stub(channel, options));
  return stub;
}

NodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_BroadcastTransaction_(NodeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BroadcastBlock_(NodeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBlockchain_(NodeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetTransactionStatus_(NodeService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NodeService::Stub::BroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::bitcoin::BroadcastTransactionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bitcoin::BroadcastTransactionRequest, ::bitcoin::BroadcastTransactionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BroadcastTransaction_, context, request, response);
}

void NodeService::Stub::async::BroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest* request, ::bitcoin::BroadcastTransactionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bitcoin::BroadcastTransactionRequest, ::bitcoin::BroadcastTransactionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BroadcastTransaction_, context, request, response, std::move(f));
}

void NodeService::Stub::async::BroadcastTransaction(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest* request, ::bitcoin::BroadcastTransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BroadcastTransaction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastTransactionResponse>* NodeService::Stub::PrepareAsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bitcoin::BroadcastTransactionResponse, ::bitcoin::BroadcastTransactionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BroadcastTransaction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastTransactionResponse>* NodeService::Stub::AsyncBroadcastTransactionRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastTransactionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBroadcastTransactionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NodeService::Stub::BroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::bitcoin::BroadcastBlockResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bitcoin::BroadcastBlockRequest, ::bitcoin::BroadcastBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BroadcastBlock_, context, request, response);
}

void NodeService::Stub::async::BroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest* request, ::bitcoin::BroadcastBlockResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bitcoin::BroadcastBlockRequest, ::bitcoin::BroadcastBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BroadcastBlock_, context, request, response, std::move(f));
}

void NodeService::Stub::async::BroadcastBlock(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest* request, ::bitcoin::BroadcastBlockResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BroadcastBlock_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastBlockResponse>* NodeService::Stub::PrepareAsyncBroadcastBlockRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bitcoin::BroadcastBlockResponse, ::bitcoin::BroadcastBlockRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BroadcastBlock_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bitcoin::BroadcastBlockResponse>* NodeService::Stub::AsyncBroadcastBlockRaw(::grpc::ClientContext* context, const ::bitcoin::BroadcastBlockRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBroadcastBlockRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NodeService::Stub::GetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::bitcoin::GetBlockchainResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bitcoin::GetBlockchainRequest, ::bitcoin::GetBlockchainResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetBlockchain_, context, request, response);
}

void NodeService::Stub::async::GetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest* request, ::bitcoin::GetBlockchainResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bitcoin::GetBlockchainRequest, ::bitcoin::GetBlockchainResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBlockchain_, context, request, response, std::move(f));
}

void NodeService::Stub::async::GetBlockchain(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest* request, ::bitcoin::GetBlockchainResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBlockchain_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bitcoin::GetBlockchainResponse>* NodeService::Stub::PrepareAsyncGetBlockchainRaw(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bitcoin::GetBlockchainResponse, ::bitcoin::GetBlockchainRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetBlockchain_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bitcoin::GetBlockchainResponse>* NodeService::Stub::AsyncGetBlockchainRaw(::grpc::ClientContext* context, const ::bitcoin::GetBlockchainRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetBlockchainRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NodeService::Stub::GetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::bitcoin::GetTransactionStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::bitcoin::GetTransactionStatusRequest, ::bitcoin::GetTransactionStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetTransactionStatus_, context, request, response);
}

void NodeService::Stub::async::GetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest* request, ::bitcoin::GetTransactionStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::bitcoin::GetTransactionStatusRequest, ::bitcoin::GetTransactionStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTransactionStatus_, context, request, response, std::move(f));
}

void NodeService::Stub::async::GetTransactionStatus(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest* request, ::bitcoin::GetTransactionStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetTransactionStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::bitcoin::GetTransactionStatusResponse>* NodeService::Stub::PrepareAsyncGetTransactionStatusRaw(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::bitcoin::GetTransactionStatusResponse, ::bitcoin::GetTransactionStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetTransactionStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::bitcoin::GetTransactionStatusResponse>* NodeService::Stub::AsyncGetTransactionStatusRaw(::grpc::ClientContext* context, const ::bitcoin::GetTransactionStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetTransactionStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

NodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::bitcoin::BroadcastTransactionRequest, ::bitcoin::BroadcastTransactionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bitcoin::BroadcastTransactionRequest* req,
             ::bitcoin::BroadcastTransactionResponse* resp) {
               return service->BroadcastTransaction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::bitcoin::BroadcastBlockRequest, ::bitcoin::BroadcastBlockResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bitcoin::BroadcastBlockRequest* req,
             ::bitcoin::BroadcastBlockResponse* resp) {
               return service->BroadcastBlock(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::bitcoin::GetBlockchainRequest, ::bitcoin::GetBlockchainResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bitcoin::GetBlockchainRequest* req,
             ::bitcoin::GetBlockchainResponse* resp) {
               return service->GetBlockchain(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NodeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NodeService::Service, ::bitcoin::GetTransactionStatusRequest, ::bitcoin::GetTransactionStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::bitcoin::GetTransactionStatusRequest* req,
             ::bitcoin::GetTransactionStatusResponse* resp) {
               return service->GetTransactionStatus(ctx, req, resp);
             }, this)));
}

NodeService::Service::~Service() {
}

::grpc::Status NodeService::Service::BroadcastTransaction(::grpc::ServerContext* context, const ::bitcoin::BroadcastTransactionRequest* request, ::bitcoin::BroadcastTransactionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::BroadcastBlock(::grpc::ServerContext* context, const ::bitcoin::BroadcastBlockRequest* request, ::bitcoin::BroadcastBlockResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::GetBlockchain(::grpc::ServerContext* context, const ::bitcoin::GetBlockchainRequest* request, ::bitcoin::GetBlockchainResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NodeService::Service::GetTransactionStatus(::grpc::ServerContext* context, const ::bitcoin::GetTransactionStatusRequest* request, ::bitcoin::GetTransactionStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace bitcoin

