// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transaction_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transaction_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transaction_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transaction_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transaction_2eproto;
namespace bitcoin {
class Transaction;
struct TransactionDefaultTypeInternal;
extern TransactionDefaultTypeInternal _Transaction_default_instance_;
}  // namespace bitcoin
PROTOBUF_NAMESPACE_OPEN
template<> ::bitcoin::Transaction* Arena::CreateMaybeMessage<::bitcoin::Transaction>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bitcoin {

// ===================================================================

class Transaction final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bitcoin.Transaction) */ {
 public:
  inline Transaction() : Transaction(nullptr) {}
  ~Transaction() override;
  explicit PROTOBUF_CONSTEXPR Transaction(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Transaction(const Transaction& from);
  Transaction(Transaction&& from) noexcept
    : Transaction() {
    *this = ::std::move(from);
  }

  inline Transaction& operator=(const Transaction& from) {
    CopyFrom(from);
    return *this;
  }
  inline Transaction& operator=(Transaction&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Transaction& default_instance() {
    return *internal_default_instance();
  }
  static inline const Transaction* internal_default_instance() {
    return reinterpret_cast<const Transaction*>(
               &_Transaction_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Transaction& a, Transaction& b) {
    a.Swap(&b);
  }
  inline void Swap(Transaction* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Transaction* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Transaction* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Transaction>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Transaction& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Transaction& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Transaction* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bitcoin.Transaction";
  }
  protected:
  explicit Transaction(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPrevTransactionHashFieldNumber = 1,
    kSenderPublicKeyFieldNumber = 2,
    kSignatureFieldNumber = 3,
    kRecipientPublicKeyFieldNumber = 4,
    kAmountFieldNumber = 5,
    kTimestampFieldNumber = 6,
  };
  // bytes prev_transaction_hash = 1;
  void clear_prev_transaction_hash();
  const std::string& prev_transaction_hash() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prev_transaction_hash(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prev_transaction_hash();
  PROTOBUF_NODISCARD std::string* release_prev_transaction_hash();
  void set_allocated_prev_transaction_hash(std::string* prev_transaction_hash);
  private:
  const std::string& _internal_prev_transaction_hash() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prev_transaction_hash(const std::string& value);
  std::string* _internal_mutable_prev_transaction_hash();
  public:

  // bytes sender_public_key = 2;
  void clear_sender_public_key();
  const std::string& sender_public_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_public_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_public_key();
  PROTOBUF_NODISCARD std::string* release_sender_public_key();
  void set_allocated_sender_public_key(std::string* sender_public_key);
  private:
  const std::string& _internal_sender_public_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_public_key(const std::string& value);
  std::string* _internal_mutable_sender_public_key();
  public:

  // bytes signature = 3;
  void clear_signature();
  const std::string& signature() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_signature(ArgT0&& arg0, ArgT... args);
  std::string* mutable_signature();
  PROTOBUF_NODISCARD std::string* release_signature();
  void set_allocated_signature(std::string* signature);
  private:
  const std::string& _internal_signature() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_signature(const std::string& value);
  std::string* _internal_mutable_signature();
  public:

  // bytes recipient_public_key = 4;
  void clear_recipient_public_key();
  const std::string& recipient_public_key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_recipient_public_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_recipient_public_key();
  PROTOBUF_NODISCARD std::string* release_recipient_public_key();
  void set_allocated_recipient_public_key(std::string* recipient_public_key);
  private:
  const std::string& _internal_recipient_public_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_recipient_public_key(const std::string& value);
  std::string* _internal_mutable_recipient_public_key();
  public:

  // uint64 amount = 5;
  void clear_amount();
  uint64_t amount() const;
  void set_amount(uint64_t value);
  private:
  uint64_t _internal_amount() const;
  void _internal_set_amount(uint64_t value);
  public:

  // uint64 timestamp = 6;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:bitcoin.Transaction)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prev_transaction_hash_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_public_key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr signature_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr recipient_public_key_;
  uint64_t amount_;
  uint64_t timestamp_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_transaction_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Transaction

// bytes prev_transaction_hash = 1;
inline void Transaction::clear_prev_transaction_hash() {
  prev_transaction_hash_.ClearToEmpty();
}
inline const std::string& Transaction::prev_transaction_hash() const {
  // @@protoc_insertion_point(field_get:bitcoin.Transaction.prev_transaction_hash)
  return _internal_prev_transaction_hash();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Transaction::set_prev_transaction_hash(ArgT0&& arg0, ArgT... args) {
 
 prev_transaction_hash_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.Transaction.prev_transaction_hash)
}
inline std::string* Transaction::mutable_prev_transaction_hash() {
  std::string* _s = _internal_mutable_prev_transaction_hash();
  // @@protoc_insertion_point(field_mutable:bitcoin.Transaction.prev_transaction_hash)
  return _s;
}
inline const std::string& Transaction::_internal_prev_transaction_hash() const {
  return prev_transaction_hash_.Get();
}
inline void Transaction::_internal_set_prev_transaction_hash(const std::string& value) {
  
  prev_transaction_hash_.Set(value, GetArenaForAllocation());
}
inline std::string* Transaction::_internal_mutable_prev_transaction_hash() {
  
  return prev_transaction_hash_.Mutable(GetArenaForAllocation());
}
inline std::string* Transaction::release_prev_transaction_hash() {
  // @@protoc_insertion_point(field_release:bitcoin.Transaction.prev_transaction_hash)
  return prev_transaction_hash_.Release();
}
inline void Transaction::set_allocated_prev_transaction_hash(std::string* prev_transaction_hash) {
  if (prev_transaction_hash != nullptr) {
    
  } else {
    
  }
  prev_transaction_hash_.SetAllocated(prev_transaction_hash, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (prev_transaction_hash_.IsDefault()) {
    prev_transaction_hash_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.Transaction.prev_transaction_hash)
}

// bytes sender_public_key = 2;
inline void Transaction::clear_sender_public_key() {
  sender_public_key_.ClearToEmpty();
}
inline const std::string& Transaction::sender_public_key() const {
  // @@protoc_insertion_point(field_get:bitcoin.Transaction.sender_public_key)
  return _internal_sender_public_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Transaction::set_sender_public_key(ArgT0&& arg0, ArgT... args) {
 
 sender_public_key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.Transaction.sender_public_key)
}
inline std::string* Transaction::mutable_sender_public_key() {
  std::string* _s = _internal_mutable_sender_public_key();
  // @@protoc_insertion_point(field_mutable:bitcoin.Transaction.sender_public_key)
  return _s;
}
inline const std::string& Transaction::_internal_sender_public_key() const {
  return sender_public_key_.Get();
}
inline void Transaction::_internal_set_sender_public_key(const std::string& value) {
  
  sender_public_key_.Set(value, GetArenaForAllocation());
}
inline std::string* Transaction::_internal_mutable_sender_public_key() {
  
  return sender_public_key_.Mutable(GetArenaForAllocation());
}
inline std::string* Transaction::release_sender_public_key() {
  // @@protoc_insertion_point(field_release:bitcoin.Transaction.sender_public_key)
  return sender_public_key_.Release();
}
inline void Transaction::set_allocated_sender_public_key(std::string* sender_public_key) {
  if (sender_public_key != nullptr) {
    
  } else {
    
  }
  sender_public_key_.SetAllocated(sender_public_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (sender_public_key_.IsDefault()) {
    sender_public_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.Transaction.sender_public_key)
}

// bytes signature = 3;
inline void Transaction::clear_signature() {
  signature_.ClearToEmpty();
}
inline const std::string& Transaction::signature() const {
  // @@protoc_insertion_point(field_get:bitcoin.Transaction.signature)
  return _internal_signature();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Transaction::set_signature(ArgT0&& arg0, ArgT... args) {
 
 signature_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.Transaction.signature)
}
inline std::string* Transaction::mutable_signature() {
  std::string* _s = _internal_mutable_signature();
  // @@protoc_insertion_point(field_mutable:bitcoin.Transaction.signature)
  return _s;
}
inline const std::string& Transaction::_internal_signature() const {
  return signature_.Get();
}
inline void Transaction::_internal_set_signature(const std::string& value) {
  
  signature_.Set(value, GetArenaForAllocation());
}
inline std::string* Transaction::_internal_mutable_signature() {
  
  return signature_.Mutable(GetArenaForAllocation());
}
inline std::string* Transaction::release_signature() {
  // @@protoc_insertion_point(field_release:bitcoin.Transaction.signature)
  return signature_.Release();
}
inline void Transaction::set_allocated_signature(std::string* signature) {
  if (signature != nullptr) {
    
  } else {
    
  }
  signature_.SetAllocated(signature, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (signature_.IsDefault()) {
    signature_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.Transaction.signature)
}

// bytes recipient_public_key = 4;
inline void Transaction::clear_recipient_public_key() {
  recipient_public_key_.ClearToEmpty();
}
inline const std::string& Transaction::recipient_public_key() const {
  // @@protoc_insertion_point(field_get:bitcoin.Transaction.recipient_public_key)
  return _internal_recipient_public_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Transaction::set_recipient_public_key(ArgT0&& arg0, ArgT... args) {
 
 recipient_public_key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bitcoin.Transaction.recipient_public_key)
}
inline std::string* Transaction::mutable_recipient_public_key() {
  std::string* _s = _internal_mutable_recipient_public_key();
  // @@protoc_insertion_point(field_mutable:bitcoin.Transaction.recipient_public_key)
  return _s;
}
inline const std::string& Transaction::_internal_recipient_public_key() const {
  return recipient_public_key_.Get();
}
inline void Transaction::_internal_set_recipient_public_key(const std::string& value) {
  
  recipient_public_key_.Set(value, GetArenaForAllocation());
}
inline std::string* Transaction::_internal_mutable_recipient_public_key() {
  
  return recipient_public_key_.Mutable(GetArenaForAllocation());
}
inline std::string* Transaction::release_recipient_public_key() {
  // @@protoc_insertion_point(field_release:bitcoin.Transaction.recipient_public_key)
  return recipient_public_key_.Release();
}
inline void Transaction::set_allocated_recipient_public_key(std::string* recipient_public_key) {
  if (recipient_public_key != nullptr) {
    
  } else {
    
  }
  recipient_public_key_.SetAllocated(recipient_public_key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (recipient_public_key_.IsDefault()) {
    recipient_public_key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bitcoin.Transaction.recipient_public_key)
}

// uint64 amount = 5;
inline void Transaction::clear_amount() {
  amount_ = uint64_t{0u};
}
inline uint64_t Transaction::_internal_amount() const {
  return amount_;
}
inline uint64_t Transaction::amount() const {
  // @@protoc_insertion_point(field_get:bitcoin.Transaction.amount)
  return _internal_amount();
}
inline void Transaction::_internal_set_amount(uint64_t value) {
  
  amount_ = value;
}
inline void Transaction::set_amount(uint64_t value) {
  _internal_set_amount(value);
  // @@protoc_insertion_point(field_set:bitcoin.Transaction.amount)
}

// uint64 timestamp = 6;
inline void Transaction::clear_timestamp() {
  timestamp_ = uint64_t{0u};
}
inline uint64_t Transaction::_internal_timestamp() const {
  return timestamp_;
}
inline uint64_t Transaction::timestamp() const {
  // @@protoc_insertion_point(field_get:bitcoin.Transaction.timestamp)
  return _internal_timestamp();
}
inline void Transaction::_internal_set_timestamp(uint64_t value) {
  
  timestamp_ = value;
}
inline void Transaction::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:bitcoin.Transaction.timestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bitcoin

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transaction_2eproto
